### ISSUE TITLE
Timed out waiting for expected messages - WebUi issue

### ISSUE THREAD

**Issue by nspiegl** [jlesage/docker-crashplan-pro#109]
Hi, I have been running this docker container for some time but just recently I seem to be having issues logging into the WebUI. The log shows this >>

```
[07.04.18 21:55:15.178 INFO  17703518-119 backup42.service.ui.UIController] UserActionRequest: LoginRequestMessage[855579153221947553] LOGIN: username=XXXXXX, password=****, serverAddress=central.crashplanpro.com:443
[07.04.18 21:55:15.178 INFO  17703518-119 backup42.service.peer.Authorizer] AUTH:: LOGIN, username=XXXXXXXX, passwordExists=true, requestMessage=LoginRequestMessage[855579153221947553] LOGIN: username=XXXXXX, password=****, serverAddress=central.crashplanpro.com:443, register=false, firstName=null, lastName=null, registrationKey=null, waitTimeMillis=120000
[07.04.18 21:55:15.179 INFO  77760_AUTH-2 backup42.service.peer.Authorizer] AUTH:: *** START *** with Authorizer@987439944[ LOGIN, username=XXXXXXXX, passwordExists=true]
[07.04.18 21:55:15.179 INFO  77760_AUTH-2 up42.service.peer.PeerController] Attempting to connect to CPC. delay=120000
[07.04.18 21:58:15.180 WARN  17703518-119 p42.service.ui.http.AHttpHandler] HTTP:: Internal error while handling HTTP-REST request., com.code42.exception.DebugRuntimeException: Timed out waiting for expected messages, 855579153205170337, LoginRequestMessage[855579153221947553] LOGIN: username=XXXXXXXX, password=****, serverAddress=central.crashplanpro.com:443, [class com.backup42.service.ui.message.LoginResponseMessage]
STACKTRACE:: com.code42.exception.DebugRuntimeException: Timed out waiting for expected messages, 855579153205170337, LoginRequestMessage[855579153221947553] LOGIN: username=XXXXXXX, password=****, serverAddress=central.crashplanpro.com:443, [class com.backup42.service.ui.message.LoginResponseMessage]
        at com.backup42.service.ui.http.HttpNetworkChannel.getResponse(HttpNetworkChannel.java:81)
        at com.backup42.service.ui.http.LegacyHttpSession.getResponse(LegacyHttpSession.java:32)
        at com.backup42.service.ui.http.LegacyHttpHandler.getResponse(LegacyHttpHandler.java:85)
        at com.backup42.service.ui.http.AHttpHandler.service(AHttpHandler.java:68)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
        at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
        at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
        at org.eclipse.jetty.server.Server.handle(Server.java:497)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
        at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
        at java.lang.Thread.run(Thread.java:748)
Caused by: com.backup42.service.ui.http.MessageCatcher$MessageCatcherTimeoutException: Id: 855579153205170337, Request message: LoginRequestMessage[855579153221947553] LOGIN: username=XXXXXXX, password=****, serverAddress=central.crashplanpro.com:443, Expecting message(s): [class com.backup42.service.ui.message.LoginResponseMessage]
        at com.backup42.service.ui.http.MessageCatcher.blockForMessages(MessageCatcher.java:113)
        at com.backup42.service.ui.http.HttpNetworkChannel.getResponse(HttpNetworkChannel.java:73)
        ... 18 more
```

Some test from within the container >>

```
/tmp # nslookup central.crashplanpro.com
nslookup: can't resolve '(null)': Name does not resolve

Name:      central.crashplanpro.com
Address 1: 216.17.8.47 cbm-msp.crashplan.com
Address 2: 216.17.8.4 central.crashplanpro.com
Address 3: 216.17.8.3 central.crashplanpro.com
Address 4: 216.17.8.51 gbm-msp.crashplan.com
Address 5: 216.17.8.48 central.crashplanpro.com



/tmp # ping central.crashplanpro.com
PING central.crashplanpro.com (216.17.8.51): 56 data bytes
64 bytes from 216.17.8.51: seq=0 ttl=44 time=320.102 ms
64 bytes from 216.17.8.51: seq=1 ttl=44 time=316.895 ms
64 bytes from 216.17.8.51: seq=2 ttl=44 time=316.988 ms
64 bytes from 216.17.8.51: seq=3 ttl=44 time=317.414 ms
^C
--- central.crashplanpro.com ping statistics ---
4 packets transmitted, 4 packets received, 0% packet loss
round-trip min/avg/max = 316.895/317.849/320.102 ms
```

The log indicates things are still working and from the crashplan website the system is online. Any clue on what could cause this ?

**Comment by nspiegl** [comment]
Clearing the cache folder made no difference either.

**Comment by jlesage** [comment]
What do you mean exactly by "issues logging into the WebUI"?  Do you mean that you can't access the CrashPlan UI?

**Comment by bigtfromaz** [comment]
@jlesage From the messages, it looks like the crashplan run time in the container is timing out waiting for authentication when it is connecting to crashplan's storage service.  It's an educated guess as I don't know the roles of the various server names in the log. 

This does not look like a DNS issue but rather a timeout that's occurring server side waiting for an authentication server to respond after sending a request. 

@nspiegl 
Is this issue persistent or transient?  In other words, does it occur every time?
Also, are you in the act of signing into crashplan from your display at the time...or is this occurring in the background.

I would open a ticket with CrashPlan, upload the messages and stack trace and see what they have to say about the issue.  This could be a container/configuration issue or it could be a problem on their side.  Their insight regarding what may have gone wrong might prove useful.

**Comment by nspiegl** [comment]
Thanks for the responses. Yes I was referring to the CrashPlan UI.

It was happening when I attempted to sign in and it just showed something like "unknown error unable to sign in", tried multiple times and got the same error on the screen and in the logs.

Today its all working so it must have been an issue on  CrashPlan's side of things. Feel free to close this issue.

**Comment by jlesage** [comment]
Great, glad it's working.
