### ISSUE TITLE
Docker Container Station Crashplan Small Business QNAP TS-451+ Issues

### ISSUE THREAD

**Issue by kbareis** [jlesage/docker-crashplan-pro#174]
Hello folks, I have been banging on this one for almost a day now. I have gotten to the point that all I see is this message in the console in Container Station (Docker) for my QNAP TS-451+
`[CrashPlanEngine] starting... `

**In the ui.log I am seeing**
`Retrying communication with service connect ECONNREFUSED 127.0.0.1:4244`

**Error from the service.log.0**
```
[05.03.19 13:42:14.523 WARN  main         backup42.common.config.AppConfig] Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL, com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
STACKTRACE:: com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
	at com.backup42.common.config.AppConfig.load(AppConfig.java:139)
	at com.backup42.common.config.ServiceConfig.load(ServiceConfig.java:421)
	at com.backup42.service.CPService.loadConfig(CPService.java:1183)
	at com.backup42.service.CPService.start(CPService.java:506)
	at com.backup42.service.CPService.main(CPService.java:1986)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.code42.jna.openssl.MD5DigestOpenSSL
	at com.code42.hash.MD5Digest.<init>(MD5Digest.java:24)
	at com.code42.utils.OsPatternList.getChecksum(OsPatternList.java:141)
	at com.code42.utils.PatternList.equals(PatternList.java:389)
	at com.code42.utils.OsPatternList.equals(OsPatternList.java:276)
	at java.util.Objects.equals(Objects.java:59)
	at com.code42.config.ConfigXmlTransformer.fromXmlConfigItem(ConfigXmlTransformer.java:558)
	at com.code42.config.ConfigXmlTransformer.fromXmlAConfigItem(ConfigXmlTransformer.java:432)
	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:332)
	at com.code42.config.ConfigXmlTransformer.fromXmlConfigComponent(ConfigXmlTransformer.java:600)
	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:334)
	at com.code42.config.ConfigXmlTransformer.fromXml(ConfigXmlTransformer.java:87)
	at com.code42.xml.XmlTool.fromXml(XmlTool.java:201)
	at com.code42.xml.XmlTool.fromXml(XmlTool.java:182)
	at com.code42.config.AConfig.fromXml(AConfig.java:77)
	at com.code42.config.AConfigFile.fromXml(AConfigFile.java:65)
	at com.backup42.common.config.AppConfig.load(AppConfig.java:136)
	... 4 more

[05.03.19 13:42:14.526 ERROR main                                         ] com.code42.exception.DebugException: Problem reading my config xml! - myConfigFile=/usr/local/crashplan/conf/my.service.xml, java.la
```

**Here's my config I have been using**
```
docker run -d \
  --name=crashplan-pro \
  -e USER_ID=0 \
  -e GROUP_ID=0 \
  -e CRASHPLAN_SRV_MAX_MEM=4096M \
  -p 5800:5800 \
  -e TZ=America/Chicago \
  -v /share/docker/appdata/crashplan-pro:/config:rw \
  -v /share/CACHEDEV1_DATA:/share:rw \
  jlesage/crashplan-pro
```

**Log Files**
Removed

**Comment by kbareis** [comment]
Just as I posted this, I think I may have figured it out. For folks that are using an antivirus on your NAS (Clam AV in my case) It appears that it may mess with the backup service. Not sure if there is anything that can be done via this project but I will leave open just-in-case. If the rest of my backup completes without issue, I will post here as well.

**Comment by jlesage** [comment]
This is to be the same issue as https://github.com/jlesage/docker-crashplan-pro/issues/173.

Do you have any update about your findings?

**Comment by kbareis** [comment]
I do, however nothing succeeded. I bumped memory to 6gb and I could get CrashPlan to run for up to an hour or two but then would fall back into waiting for connection. I read the other ticket you linked and I am also using a custom key. I originally tried to take over an existing backup and that didn’t work at all. Then I tried doing a fresh backup and that was the one I could only get working for a couple hours before it went back into the waiting loop

**Comment by jlesage** [comment]
Is the "waiting loop" you are talking about the same issue as originally reported (i.e. crashplan engine not able to start)?

**Comment by kbareis** [comment]
Yes. Going to try v2.6.2 as the other person suggested to see if I can get it working.

**Comment by kbareis** [comment]
Couldn't even login using v.2.6.2. Resetting up via latest version and will post screenshots, logs, and configs in a bit.

**Comment by kbareis** [comment]
Backup failed at 8.40 about an hour after it started. In total, I got like 2.5 GB up. The thing failed so hard it locked up my NAS. I think it may be an issue with QNAPs implementation of Docker. Images and logs attached in the zip file.

[Docker GitHub Stuff.zip](https://github.com/jlesage/docker-crashplan-pro/files/3148225/Docker.GitHub.Stuff.zip)

**Comment by jlesage** [comment]
It seems that you are now getting a different issue. `service.log.0` is flooded by the same exception.

Can you try to chat with the CrashPlan's support team and provide your `service.log.0` log file to see what they have to say about it?

**Comment by kbareis** [comment]
I ended up moving away from my Qnap device. Unraid works perfectly with this container. Assuming it has to do with Qnap's use of Docker.
