### ISSUE TITLE
Version mismatch - You must upgrade to use this destination

### ISSUE THREAD

**Issue by geeksrus** [jlesage/docker-crashplan-pro#243]
Hi,
I've been using this for a while now without any issue. For the last 6 days, I'm getting this message when I logged into the web UI "Version mismatch - You must upgrade to use this destination" and my backup is not running.  What do I need to do?  According to the UI, I'm running version 8.0.0.778.  I'm running this on Docker on my Synology NAS. I've tried restarting the container but that did not fix.

Thanks

**Comment by radzio** [comment]
Same here on QNAP

**Comment by jlesage** [comment]
I don't see a new version on my side.  Can you log in you account on crashplanpro.com and check if you have a new available app version ?

**Comment by geeksrus** [comment]
No, when I logged into crashplanpro.com, under App Download, I see the version for Linux is 8.0.0 build 778.  So doesn't seem to be a new app version.

**Comment by jlesage** [comment]
Ok, you can also check in `service.log.0`: you should see messages indicating that CP tries to download an update... can you provide them ?

**Comment by geeksrus** [comment]
I got this message when I tried using Putty to SSH into the Docker container:
OCI runtime exec failed: exec failed: container_linux.go:345: starting container process caused "exec: \"/bin/bash\": stat /bin/bash: no such file or directory": unknown

**Comment by uberwrensch** [comment]
Try `/bin/sh` or `/bin/ash`.

**Comment by jlesage** [comment]
The file is accessible at `log/service.log.0`, under the folder you mapped to `/config` (no need to login to the container).

**Comment by geeksrus** [comment]
I'm not sure if this is what you're looking for, but I see a lot of these in the service.log.0:

[06.15.20 03:59:04.475 INFO  WeDftWkr1535 ervice.peer.PeerVersionValidator] WE have an old version, localVersion=1525200006800, remoteVersion=1525200006811, remoteGuid=7497247104854324461
[06.15.20 04:04:03.371 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=3, numFailedConnectedCheck=0, duration(ms)=0
[06.15.20 04:09:03.371 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=3, numFailedConnectedCheck=0, duration(ms)=0
[06.15.20 04:14:03.372 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=3, numFailedConnectedCheck=0, duration(ms)=0
[06.15.20 04:19:03.372 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=3, numFailedConnectedCheck=0, duration(ms)=0
[06.15.20 04:24:03.373 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=3, numFailedConnectedCheck=0, duration(ms)=0
[06.15.20 04:29:02.953 INFO  -PAC RUNNING proxy.ProxyAutoConfigServiceImpl] PROXY:: Updating proxy on regular interval
[06.15.20 04:29:03.374 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup Disconnecting inactive peer. RemotePeer-[guid=42, SERVER]; PeerConnectionState-[state=CONNECTED, layer=1/1(Peer::Sabre), connecting=2020-06-15T03:59:03:775, connected=2020-06-15T03:59:04:337, attempts=0, connectActivity=2020-06-15T03:59:04:337, keepAliveSent=2020-06-15T04:24:03:373, minRetry=26870, reconnectable, addressGenerator=PeerAddressGenerator [locationPairs=[(direct) [=> 42@162.222.40.245:4282], (direct) [=> 42@162.222.40.245:443]], currentAddressIndex=0, unresolvedPrimary=[[42@cxc-sea.crashplan.com:4282(server)], transportPbK=X509.checksum(8bb65b77ee22a8e95d5e742728934c5a)], unresolvedSecondary=Optional[[[42@cxc-sea.crashplan.com:443]]], pacReader=com.code42.messaging.proxy.pac.ProxyAutoConfigReader@2f973695, Reset(2020-06-15T03:59:03.426)]]; Session-[id=958727203576251922, layer=Peer::Sabre, closed=false, expiration=null, valid=Optional[false], isAcceptor=false, remoteIdentity=STORAGE, completedAuth=true, lat=2020-06-15T04:24:03:374, lrt=2020-06-15T03:59:04:474, lwt=2020-06-15T04:24:03:374, enqueued=false, local=172.17.0.12:51926, remote=162.222.40.245:4287, usingProtos=true, sessionState=SabreSessionState[], remoteSessionId=958727203467238473, WAN]
[06.15.20 04:29:03.374 INFO  DefaultGroup .code42.messaging.peer.PeerGroup] PG::DefaultGroup DONE Managing connected remote peers. numConnected=3, numFailedConnectedCheck=1, duration(ms)=1
[06.15.20 04:29:03.385 INFO  re-event-2-2 .handler.ChannelLifecycleHandler] SABRE:: Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=[id: 0xd7826ae2, L:/172.17.0.12:51926 ! R:/162.222.40.245:4287], sessionState=RemotePeer-[guid=42, state=CONNECTED]; Session-[localID=958727203576251922, remoteID=958727203467238473, layer=Peer::Sabre, closed=true, expiration=null, remoteIdentity=STORAGE, local=172.17.0.12:51926, remote=162.222.40.245:4287]
[06.15.20 04:29:03.439 INFO  DefaultGroup tore.BackupClientRestoreDelegate] BC::stopRestore(): idPair=727225959197707875>42, selectedForRestore=false, event=STOP_REQUESTED canceled=false
[06.15.20 04:29:03.439 INFO  DefaultGroup tore.BackupClientRestoreDelegate] BC::Not selected for restore
[06.15.20 04:29:03.439 INFO  DefaultGroup tore.BackupClientRestoreDelegate] BC::0 pending restore canceled
[06.15.20 04:29:03.440 INFO  DefaultGroup com.code42.backup.BackupEntityV1] BC[727225959197707875>42:: Setting keepBlockState=0 during reset(); BC[727225959197707875>42, sameOwner=f, backupConnected=f, authorized=f, usingForBackup=t, backupNotReadyCode=NOT_AVAILABLE, backingUp=f, validating=f, closing=f, keepBlockState=0, con=0, val=0, readyCheckTime=0, MM[BT 727225959197707875>42: openCount=0, initialized = true, dataFiles.open = false, /usr/local/crashplan/cache/42], session=null, hosted=t, hostedCloud=t, replacing=f, selectedForBackup=f, selectedForRestore=f, validationNeeded=f, backupUsageTime=0, cacheMaintenanceState=null, restoreUtil=BackupClientRestoreDelegate [restoreControl=RestoreReceiveControl@684844445[ , hasRestoreEnv=false, hasRestoreJob=false ], selectedForRestore=false, remoteRestoreStats=RestoreStats[BT sourceId = 727225959197707875, targetId = 42, restoreId = 0, selectedForRestore = false, restoring = false, completed = false, completedTimeInMillis = null, stopwatch = 2day 3hr, numFilesToRestore = 0, numBytesToRestore = 0, numFilesRestored = 0, numBytesRestored = 0, %complete = 100.00%, receiveRateInBytesPerSec(B/s) = 0.000, sendRateInBytesPerSec(B/s) = 0.000, estimatedTimeRemaining = 0.000, fileNumBytesToRestore = 0, fileNumBytesRestored = 0, %completeCurrentFile = 100.00%, numSessionFilesRestored = 0, numSessionBytesRestored = 0, problemCount = 0], pendingRestoresCount=0], BackupQueue[727225959197707875>42, running=f, #tasks=0, sets=[BackupFileTodoSet[backupSetId=1, guid=42, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@484262754[ path = /usr/local/crashplan/cache/cpft1_42, closed = false, dataSize = 10915366, headerSize = 0], numTodos = 95419, numBytes = 45760446131]]], env=null, TodoWorker@2013118018[ threadName = BQTodoWkr-42, stopped = true], TaskWorker@817093103[ threadName = BQTaskWrk-42, stopped = true]] ]; 
[06.15.20 04:29:03.440 INFO  DefaultGroup com.code42.backup.BackupEntityV1] BC[727225959197707875>42:: 727225959197707875>42 DISCONNECTED. UNKNOWN RemotePeer-[guid=42, state=DISCONNECTED]; Session-[localID=958727203576251922, remoteID=958727203467238473, layer=Peer::Sabre, closed=true, expiration=null, remoteIdentity=STORAGE, local=172.17.0.12:51926, remote=162.222.40.245:4287]; BC[727225959197707875>42, sameOwner=f, backupConnected=f, authorized=f, usingForBackup=t, backupNotReadyCode=NOT_AVAILABLE, backingUp=f, validating=f, closing=f, keepBlockState=0, con=0, val=0, readyCheckTime=0, MM[BT 727225959197707875>42: openCount=0, initialized = true, dataFiles.open = false, /usr/local/crashplan/cache/42], session=null, hosted=t, hostedCloud=t, replacing=f, selectedForBackup=f, selectedForRestore=f, validationNeeded=f, backupUsageTime=0, cacheMaintenanceState=null, restoreUtil=BackupClientRestoreDelegate [restoreControl=RestoreReceiveControl@684844445[ , hasRestoreEnv=false, hasRestoreJob=false ], selectedForRestore=false, remoteRestoreStats=RestoreStats[BT sourceId = 727225959197707875, targetId = 42, restoreId = 0, selectedForRestore = false, restoring = false, completed = false, completedTimeInMillis = null, stopwatch = 2day 3hr, numFilesToRestore = 0, numBytesToRestore = 0, numFilesRestored = 0, numBytesRestored = 0, %complete = 100.00%, receiveRateInBytesPerSec(B/s) = 0.000, sendRateInBytesPerSec(B/s) = 0.000, estimatedTimeRemaining = 0.000, fileNumBytesToRestore = 0, fileNumBytesRestored = 0, %completeCurrentFile = 100.00%, numSessionFilesRestored = 0, numSessionBytesRestored = 0, problemCount = 0], pendingRestoresCount=0], BackupQueue[727225959197707875>42, running=f, #tasks=0, sets=[BackupFileTodoSet[backupSetId=1, guid=42, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@484262754[ path = /usr/local/crashplan/cache/cpft1_42, closed = false, dataSize = 10915366, headerSize = 0], numTodos = 95419, numBytes = 45760446131]]], env=null, TodoWorker@2013118018[ threadName = BQTodoWkr-42, stopped = true], TaskWorker@817093103[ threadName = BQTaskWrk-42, stopped = true]] ]; 
[06.15.20 04:29:06.925 INFO  re-event-2-3                      SabreLogger] TLS connection established. initiator=true, provider=SSLEngineImpl, version=TLSv1.2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, channel=[id: 0x8d9c20cf, L:/172.17.0.12:53085 - R:/162.222.40.245:4287]
[06.15.20 04:29:07.063 INFO  DefaultGroup .service.auth.AccessTokenService] ACCESS_TOKEN:: Access token request has been scheduled.
[06.15.20 04:29:07.073 INFO  eduledSrvc-0 .service.auth.AccessTokenService] ACCESS_TOKEN:: Requesting access token from authority:  https://www.crashplanpro.com
[06.15.20 04:29:07.200 ERROR eduledSrvc-0 .service.auth.AccessTokenService] ACCESS_TOKEN:: Could not complete call to authority. Reasons for failure: {}, com.code42.rest.RestRequester$RequestFailedException: Failed to execute HTTP request POST https://www.crashplanpro.com/c42api/v3/oauth/token?grant_type=client_credentials HTTP/1.1
STACKTRACE:: com.code42.rest.RestRequester$RequestFailedException: Failed to execute HTTP request POST https://www.crashplanpro.com/c42api/v3/oauth/token?grant_type=client_credentials HTTP/1.1
	at com.code42.rest.RestRequester.makeRequest(RestRequester.java:444)
	at com.code42.rest.RestRequester$RequestBuilder.execute(RestRequester.java:806)
	at com.code42.rest.RestRequester$RequestBuilder.execute(RestRequester.java:755)
	at com.code42.service.auth.AccessTokenService.requestAccessToken(AccessTokenService.java:130)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to www.crashplanpro.com:443 [www.crashplanpro.com/216.17.8.19] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:158)
	at org.apache.http.impl.conn.BasicHttpClientConnectionManager.connect(BasicHttpClientConnectionManager.java:338)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:107)
	at com.code42.rest.RestRequester.lambda$makeRequest$1(RestRequester.java:426)
	at com.code42.rest.RestRequester.makeRequest(RestRequester.java:442)
	... 9 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.base/java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:337)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:141)
	... 19 more

**Comment by radzio** [comment]
I've checked my logs. But... after updating QNAP Container Station and restarting docker image everything is working fine...

**Comment by geeksrus** [comment]
> I've checked my logs. But... after updating QNAP Container Station and restarting docker image everything is working fine...

I just tried that on my Synology and it is still an issue for me.

**Comment by geeksrus** [comment]
I opened a ticket with Code42 yesterday and this is their email today.  I tried the deauthorize steps and my backup seems to be working now.  Thank you all for your assistance!

Hello,

Thank you for contacting Code42 support!

We've seen this happen with our upgrade to version 8.0. Can I please have you perform the following.

To sign out of CrashPlan you will want to use this:

Open the Code42 CrashPlan app
Use the keyboard shortcut to open the Command Line
Mac: Option+Command+C
Windows/Linux: Ctrl+Shift+C
Enter in: deauthorize
This will log you out of the app.
Sign back in and let the synchronization process complete.
If this does not resolve the issue, please let me know!

Best regards,
Kelsey S.
CrashPlan For Small Business
Code42 Technical Support
Contact us via live chat support

**Comment by schmidtt** [comment]
Same issue here;  "Version mismatch - You must upgrade to use this destination".  Same solution as geeksrus worked.

From the console, I did "Ctrl+Shift+C", then Entered in: "deauthorize".

It logged me out of the app.  I logged back in, re-entered the encryption key, and backup process restarted at "Scanning backup selection".

Thanks jlesage. 👍
