### ISSUE TITLE
Error: Code42 cannot connect to its background service

### ISSUE THREAD

**Issue by nnit-TroelsJensen** [jlesage/docker-crashplan-pro#253]
First of all thanks for all you hard work! Very much appreciated 😃 

For the last 45 days or so any version of the container i have upgraded to has given me this error.
I couldn't find any similar issues. Do you have any ideas for troubleshooting?

![image](https://user-images.githubusercontent.com/11349349/88491223-d943b980-cfa1-11ea-8f80-7900d2ebfafb.png)

**Comment by itsthejb** [comment]
See https://github.com/jlesage/docker-crashplan-pro/issues/251#issuecomment-664459663

**Comment by jlesage** [comment]
Could you provide the container's log (`docker logs <name of the container>`)?

Also, look the following log files, located under the directory you mapped to `/config`:

- log/engine_error.log
- log/engine_output.log
- log/service.log.0

**Comment by jeremydelattre59** [comment]
Hello, 

I have the same problem since version 2.12.0

You can find logs in attachment.

Thanks for your work and your help

[service.log.0.log](https://github.com/jlesage/docker-crashplan-pro/files/5002806/service.log.0.log)
[engine_error.log](https://github.com/jlesage/docker-crashplan-pro/files/5002811/engine_error.log)
[engine_output.log](https://github.com/jlesage/docker-crashplan-pro/files/5002812/engine_output.log)

**Comment by nnit-TroelsJensen** [comment]
Here are my logs... sorry for the delay
[engine_error.log](https://github.com/jlesage/docker-crashplan-pro/files/5006551/engine_error.log)
[engine_output.log](https://github.com/jlesage/docker-crashplan-pro/files/5006553/engine_output.log)
[service.log.0.log](https://github.com/jlesage/docker-crashplan-pro/files/5006555/service.log.0.log)
[docker_log.txt](https://github.com/jlesage/docker-crashplan-pro/files/5006558/docker_log.txt)

This might be the problem:
```
[07.31.20 00:28:17.181 INFO  main         om.backup42.service.IdentityInfo] IdentityInfo.origin=file: /var/lib/crashplan/.identity
[07.31.20 00:28:17.307 WARN  main         .storage.UniversalStorageService] SM:: com.code42.exception.DebugException: INVALID MODEL! My computer not found for guid=958140816913336298, com.code42.exception.DebugException: INVALID MODEL! My computer not found for guid=958140816913336298
STACKTRACE:: com.code42.exception.DebugException: INVALID MODEL! My computer not found for guid=958140816913336298
	at com.backup42.service.model.ServiceModelService.verifyGuidMatchesIdentityAndDeauthorizeOnMismatch(ServiceModelService.java:152)
	at com.backup42.service.model.ServiceModelService.getModel(ServiceModelService.java:120)
	at com.backup42.service.ClientServiceManager.startPlatform(ClientServiceManager.java:202)
	at com.backup42.service.CPService.startPlatform(CPService.java:737)
	at com.backup42.service.CPService.start(CPService.java:462)
	at com.backup42.service.CPService.main(CPService.java:1706)

[07.31.20 00:28:17.366 WARN  main           com.backup42.service.CPService] DEAUTHORIZE - Invalid model! My computer not found for guid=958140816913336298, generateNewGuid=false, oldGuid=958140816913336298, newGuid=958140816913336298, loggingIn=false, authorized=true, reauthorizeError=CPErrors.Reauthorize.INVALID_MODEL
[07.31.20 00:28:17.521 INFO  main         om.backup42.service.AppLogWriter] WRITE app.log in 135ms
[07.31.20 00:28:17.522 INFO  main           com.backup42.service.CPService] DEAUTHORIZE FINISHED
[07.31.20 00:28:17.524 ERROR main         p42.service.ClientServiceManager] CSM:: Failed to start platform services., com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.service.ui.UIService not allowed.
STACKTRACE:: com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.service.ui.UIService not allowed.
	at com.backup42.service.ClientServiceManager.getInstance(ClientServiceManager.java:667)
	at com.backup42.service.CPService.deauthorizeImpl(CPService.java:1940)
	at com.backup42.service.CPService.lambda$deauthorizeWithGuid$8(CPService.java:1881)
	at com.backup42.service.peer.Authorizer.run(Authorizer.java:1683)
	at com.backup42.service.CPService.deauthorizeWithGuid(CPService.java:1881)
	at com.backup42.service.CPService.deauthorize(CPService.java:1867)
	at com.backup42.service.model.ServiceModelService.verifyGuidMatchesIdentityAndDeauthorizeOnMismatch(ServiceModelService.java:156)
	at com.backup42.service.model.ServiceModelService.getModel(ServiceModelService.java:120)
	at com.backup42.service.ClientServiceManager.startPlatform(ClientServiceManager.java:202)
	at com.backup42.service.CPService.startPlatform(CPService.java:737)
	at com.backup42.service.CPService.start(CPService.java:462)
	at com.backup42.service.CPService.main(CPService.java:1706)

[07.31.20 00:28:17.526 ERROR main           com.backup42.service.CPService] Error starting up, com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.service.ui.UIService not allowed.
STACKTRACE:: com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.service.ui.UIService not allowed.
	at com.backup42.service.ClientServiceManager.getInstance(ClientServiceManager.java:667)
	at com.backup42.service.CPService.deauthorizeImpl(CPService.java:1940)
	at com.backup42.service.CPService.lambda$deauthorizeWithGuid$8(CPService.java:1881)
	at com.backup42.service.peer.Authorizer.run(Authorizer.java:1683)
	at com.backup42.service.CPService.deauthorizeWithGuid(CPService.java:1881)
	at com.backup42.service.CPService.deauthorize(CPService.java:1867)
	at com.backup42.service.model.ServiceModelService.verifyGuidMatchesIdentityAndDeauthorizeOnMismatch(ServiceModelService.java:156)
	at com.backup42.service.model.ServiceModelService.getModel(ServiceModelService.java:120)
	at com.backup42.service.ClientServiceManager.startPlatform(ClientServiceManager.java:202)
	at com.backup42.service.CPService.startPlatform(CPService.java:737)
	at com.backup42.service.CPService.start(CPService.java:462)
	at com.backup42.service.CPService.main(CPService.java:1706)

[07.31.20 00:28:17.537 INFO  main           com.backup42.service.CPService] *****  STOPPING  *****
[07.31.20 00:28:17.540 INFO  Thread-0       com.backup42.service.CPService] ShutdownHook...calling cleanup
[07.31.20 00:28:17.550 INFO  STOPPING       com.backup42.service.CPService] SHUTDOWN:: Stopping service...
[07.31.20 00:28:17.558 WARN  Thread-0       com.backup42.service.CPService] SHUTDOWN:: Unable to stop threads (cleanup), java.util.concurrent.ExecutionException: com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.service.ui.UIService not allowed.
STACKTRACE:: java.util.concurrent.ExecutionException: com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.service.ui.UIService not allowed.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
	at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
	at com.backup42.service.CPService.cleanup(CPService.java:1364)
	at com.backup42.service.CPService.lambda$start$0(CPService.java:440)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.service.ui.UIService not allowed.
	at com.backup42.service.ClientServiceManager.getInstance(ClientServiceManager.java:667)
	at com.backup42.service.CPService.cleanupImpl(CPService.java:1390)
	at com.backup42.service.CPService.lambda$cleanup$4(CPService.java:1363)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
	... 1 more

[07.31.20 00:28:17.682 INFO  Thread-0                     ThreadDumpLogger] 2020-07-31 00:28:17
Full thread dump OpenJDK 64-Bit Server VM (11.0.4+11)
```

or this (if they are not related):
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.code42.crypto.jce.ec.EcCurveLookup (file:/usr/local/crashplan/lib/c42-crypto-impl-13.1.0.jar) to method sun.security.util.CurveDB.lookup(java.security.spec.ECParameterSpec)
WARNING: Please consider reporting this to the maintainers of com.code42.crypto.jce.ec.EcCurveLookup
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
[main] INFO org.reflections.Reflections - Reflections took 7851 ms to scan 35 urls, producing 1751 keys and 8860 values 
```

**Comment by jlesage** [comment]
Can you try the latest image, which include the new version published by CrashPlan?

**Comment by jeremydelattre59** [comment]
> Can you try the latest image, which include the new version published by CrashPlan?

I have the same problem. I also increase memory from 8GB to 12GB.
I have this message before service stop and start again :

> [08.06.20 06:16:11.453 ERROR main           com.backup42.service.CPService] Error starting up, java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[KeystoreService [FAILED]]}
STACKTRACE:: java.lang.IllegalStateException: Expected to be healthy after starting. The following services are not running: {FAILED=[KeystoreService [FAILED]]}
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.checkHealthy(ServiceManager.java:743)
	at com.google.common.util.concurrent.ServiceManager$ServiceManagerState.awaitHealthy(ServiceManager.java:570)
	at com.google.common.util.concurrent.ServiceManager.awaitHealthy(ServiceManager.java:330)
	at com.backup42.service.ClientServiceManager.startUniversalServices(ClientServiceManager.java:264)
	at com.backup42.service.CPService.startServices(CPService.java:2781)
	at com.backup42.service.CPService.start(CPService.java:612)
	at com.backup42.service.CPService.main(CPService.java:1723)
	Suppressed: com.google.common.util.concurrent.ServiceManager$FailedService: KeystoreService [FAILED]
	Caused by: com.code42.exception.DebugRuntimeException: Unable to load keystore
		at com.code42.service.ui.http.KeystoreService.init(KeystoreService.java:171)
		at com.code42.service.ui.http.KeystoreService.startUp(KeystoreService.java:104)
		at com.google.common.util.concurrent.AbstractIdleService$DelegateService$1.run(AbstractIdleService.java:62)
		at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
		at java.base/java.lang.Thread.run(Unknown Source)
	Caused by: java.io.IOException: Keystore was tampered with, or password was incorrect
		at java.base/sun.security.provider.JavaKeyStore.engineLoad(Unknown Source)
		at java.base/sun.security.util.KeyStoreDelegator.engineLoad(Unknown Source)
		at java.base/java.security.KeyStore.load(Unknown Source)
		at com.code42.service.ui.http.KeystoreService.loadKeystore(KeystoreService.java:210)
		at com.code42.service.ui.http.KeystoreService.init(KeystoreService.java:165)
		... 4 more
	Caused by: java.security.UnrecoverableKeyException: Password verification failed
		... 9 more

[log.zip](https://github.com/jlesage/docker-crashplan-pro/files/5032529/log.zip)

**Comment by jlesage** [comment]
Are you using your own encryption key for the backup ?

I think the issue may be with CrashPlan itself, so you could try to contact CrashPlan support and report the error (without mentioning your are using Docker).

**Comment by jeremydelattre59** [comment]
this is the response from code42

Hello,

Thank you for contacting Code42 Support.

The error from your screenshot is indicating that the CrashPlan/Code42 app is having an issue connecting to the cloud. Below is a snippet of your CrashPlan app log:

[08.06.20 06:21:12.980 INFO  main         e42.net.ClientConnectivityTester] Connectivity testing localhost, port=4242, connectionTimeout(ms)=100, retryDuration(ms)=100
[08.06.20 06:21:13.082 INFO  main         e42.net.ClientConnectivityTester] Failed to connect after duration=102, retryDuration=100, address=localhost, connectTimeout=100, e=Connection refused (Connection refused)

I would recommend checking over this list of applications that are known to cause issues with CrashPlan

https://support.code42.com/CrashPlan/6/Troubleshooting/Known_Conflicts_With_The_Code42_CrashPlan_Application
If you have resolved issues with security programs, I would take a look at firewall settings.

We have many IP addresses for our servers that can change. We usually recommend whitelisting these sites:

*.code42.com 
*.crashplan.com 
*.crashplanpro.com

We would want to make sure that port 443, 4242, 4243, 4244, and 4287 not blocked as well.

* https://support.code42.com/Administrator/Small_Business/Get_started_with_CrashPlan_for_Small_Business/CrashPlan_for_Small_Business_requirements#Network_ports

**Comment by jlesage** [comment]
I have the same messages as you about the ClientConnectivityTester.  So I don't think this is the problem.

The problem seems related to the errors/exceptions about the keystore.

**Comment by jeremydelattre59** [comment]
Hello,
This in the new response from code42 

Hello,

Thank you for the update.

Reviewing the Keystore error in the log, it is related to the CrashPlan app (8.2.2) installation error. There may have been a lingering folder from a previous CrashPlan/Code42 install that did not get removed when you reinstalled or updated the app.

I would recommend trying again to reinstall the CrashPlan app with the latest app update. Also, it is recommended not to install the CrashPlan app logged in as the ROOT user.

Below is a guide on how to reinstall the CrashPlan app:

To completely uninstall the Code42 app from your device, please follow the Complete Uninstall steps, using the instructions linked below:

Uninstalling And Reinstalling The Code42 App > Complete Uninstall
After uninstalling, you can download the latest version of the Code42 app by signing into the Code42 Console and selecting App Downloads on the left, then selecting the installer appropriate for your operating system. You can check out the video link below for a helpful guide to the process:

Install the Code42 app Video
Please note: To better protect your account and data, CrashPlan for Small Business requires you to enter the account password each time you open the Code42 app.

Please let me know if you have any other questions.

Thank you,

Christopher T.
CrashPlan For Small Business
Code42 Technical Support
Contact us via live chat support

**Comment by jlesage** [comment]
Thanks, this is interesting information.

Can you try the following steps:

- Stop the container.
- Rename the `.pki` folder to  to `.pki-old`.  This `.pki` directory is under directory you mapped to `/config`.
- Start the container.

**Comment by nnit-TroelsJensen** [comment]
Sorry for the late answer. rename .pki didn't work for me.

**Comment by jeremydelattre59** [comment]
> Sorry for the late answer. rename .pki didn't work for me.

It's the same for me

**Comment by jeremydelattre59** [comment]
Hello,
for information, my problem is solved after upgraded my qnap firmware to 4.4.3.1400 and reinstall from scratch the latest version of crashplan-pro container.
It's all right after replace previous device with new and skip transfert.

Thanks,
Jeremy

**Comment by nnit-TroelsJensen** [comment]
Yes. I finnally took myself together and reinstalled the image from scratch. And after some rreconnecting to my existing backupset i got it working. So the problem was my older version breaking somehow. Don't know how or what though.

**Comment by dcbasso** [comment]
Only works over Docker? I could not understand the fix.
