### ISSUE TITLE
unable to sign in. Unknown error

### ISSUE THREAD

**Issue by Craigabc** [jlesage/docker-crashplan-pro#283]
Hi,

Trying to install Crashplan on my home server.  I'm running v5 of OMV (Debian core). I've copied the code from the Github page and (making changes for my volumes and user) and installed it vis command line.  The CLI install all seems to work and start up.  When I go to MYIP:5800 I get the code42 login page which asks for email and then password.  I then get a "Unable to sign in. Unknown error" message.  I can logon to the code42 crashplan console (https://www.crashplanpro.com/login/#/login) with these credentials and it shows a docker-crashplan-OMV device.

I can remote in with /bin/ash and ping a number of IP addresses and websites quite happily.

What is more confusing is when I stop the container it then hangs if I restart it and won't get past "starting crashplanpro"

**Comment by jlesage** [comment]
So you are getting the problem on a first install ?  I never worked before ?

**Comment by Craigabc** [comment]
Yes,

It is at first install and has never worked.
 It installs OK and run fine the first time until login then will not let me log in.
If i then restart it will not restart correctly.

**Comment by jlesage** [comment]
Can yo usare the command you used to create the container ?

You can also have to look at `/config/log/service.log.0`, were we can get details about the failure(s).

**Comment by Craigabc** [comment]
Hi CLI

version: '3'
services:
  crashplan-pro:
    hostname: docker-crashplan-OMV
    container_name: crashplan-pro
    image: jlesage/crashplan-pro
    environment:
      - "USER_ID=998"
      - "GROUP_ID=100"
    ports:
      - "5800:5800"
    volumes:
      - "/srv/acf471e9-e95f-49ab-9caa-69df28d5b158/Config/crashplanconfig:/config:rw"
      - "/srv/acf471e9-e95f-49ab-9caa-69df28d5b158:/storage:rw"

**Comment by Craigabc** [comment]
There are over 300,000 lines in the log file.  The latest error is

[02.08.21 14:35:41.375 ERROR main                                         ] Exception in thread "main"
[02.08.21 14:35:41.375 ERROR main                                         ] java.lang.NullPointerException
[02.08.21 14:35:41.376 ERROR main                                         ]     at com.backup42.service.IdentityInfo.getGuid(IdentityInfo.java:250)
[02.08.21 14:35:41.376 ERROR main                                         ]     at com.backup42.service.CPService.getMyGuid(CPService.java:2322)
[02.08.21 14:35:41.377 ERROR main                                         ]     at com.backup42.service.CPService.exit(CPService.java:1641)
[02.08.21 14:35:41.377 ERROR main                                         ]     at com.backup42.service.CPService.start(CPService.java:710)
[02.08.21 14:35:41.377 ERROR main                                         ]     at com.backup42.service.CPService.main(CPService.java:1610)
[02.08.21 14:35:41.379 INFO  Thread-0       com.backup42.service.CPService] ShutdownHook...calling cleanup
[02.08.21 14:35:41.386 INFO  STOPPING       com.backup42.service.CPService] SHUTDOWN:: Stopping service...
[02.08.21 14:35:41.391 WARN  Thread-0       com.backup42.service.CPService] SHUTDOWN:: Unable to stop threads (cleanup), java.util.concurrent.ExecutionExcepti$
STACKTRACE:: java.util.concurrent.ExecutionException: com.code42.exception.DebugRuntimeException: Unauthorized call to unbound class class com.backup42.servic$
        at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
        at com.backup42.service.CPService.cleanup(CPService.java:1266)

**Comment by jlesage** [comment]
We probably need more content from the log since these messages don't provide clues on what's happening.

**Comment by spinks88** [comment]
I am having the same issue and I have been through everything cant get any answers
Ive tried multiple crashplan pro accounts.
Done a traceroute from the container and it gets the CP servers.

Here is the my last log.

[03.29.21 05:07:42.977 INFO  525668766-72 backup42.service.ui.UIController] UserActionRequest: LoginRequestMessage[1000336240739114212] LOGIN: username=thecpaccounts, password=****, serverAddress=central.crashplanpro.com:443
[03.29.21 05:07:42.978 INFO  525668766-72 backup42.service.peer.Authorizer] AUTH:: LOGIN, username=thecpaccounts, passwordExists=true, requestMessage=LoginRequestMessage[1000336240739114212] LOGIN: username=thecpaccounts, password=****, serverAddress=central.crashplanpro.com:443, register=false, firstName=null, lastName=null, registrationKey=null, waitTimeMillis=30000
[03.29.21 05:07:42.978 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: *** START *** with Authorizer@1676684410[ LOGIN, username=thecpaccounts, passwordExists=true]
[03.29.21 05:07:42.979 INFO  41696_AUTH-2 up42.service.peer.PeerController] Attempting to connect to CPC. delay=30000
[03.29.21 05:07:45.690 INFO  re-event-5-3                      SabreLogger] TLS connection established. initiator=true, provider=OpenSslEngine, version=TLSv1.2, cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384, channel=[id: 0xee2b0387, L:/172.17.0.2:57370 - R:/67.222.252.32:443]
[03.29.21 05:07:46.230 INFO  er3WeDftWkr8 ervice.peer.PeerVersionValidator] WE have an old version, localVersion=1525200006720 (2018-05-01T18:40:06:720+0000), remoteVersion=1525200006910 (2018-05-01T18:40:06:910+0000), remoteGuid=42
[03.29.21 05:07:46.266 INFO  er3WeDftWkr8 kup42.service.model.ServiceModel] Saved ServiceModel to disk, 3048 bytes.
[03.29.21 05:07:46.282 INFO  41696_AUTH-2 up42.service.peer.PeerController]   Connected to CPC after 3sec 
[03.29.21 05:07:46.282 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: Authority address: central.crashplanpro.com/67.222.252.32
[03.29.21 05:07:46.282 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: Beginning authorization with Authorizer@1676684410[ LOGIN, username=thecpaccounts, passwordExists=true]
[03.29.21 05:07:46.282 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: Getting auth rules. CPCAuthRulesRequestMessage@1832373876[ login=true, username=thecpaccounts, registrationKey=null ]
[03.29.21 05:07:46.555 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: AuthorizeRules [ldap=false, minPasswordLength=5, usernameIsAnEmail=true, deferredAllowed=true]
[03.29.21 05:07:46.561 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: KEYS:: Sending to authority for login/register: ArchiveDataKeys@1958215146[ securityKeyType=AccountPassword, dataKey-checksum=79ba4f25f53e8e096c40a4e74626352d, secureDataKey-checksum=6026cbdff2547a41f5caea273f839265, secureDataKeyQA-checksum=null ]
[03.29.21 05:07:46.592 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: CPCLoginMessage@1660316092[ guid=1000336238608407780, productVersion=7.2.0, username=thecpaccounts, password=true, register=false, registrationKey=null, configDate=null, socialNetworkDate=0, securityKeyType=AccountPassword, dataKey[checksum]=79ba4f25f53e8e096c40a4e74626352d, dataKeyChecksum=79ba4f25f53e8e096c40a4e74626352d, secureDataKey[checksum]=6026cbdff2547a41f5caea273f839265, orgType=BUSINESS, computerType=COMPUTER, address=172.17.0.2:4242, computerName = 82df3491b248, challengeResponse=false, externalAuthenticatorSessionId=null, duplicateGuidDetectionCounter=19, guidGenerated=true ]
[03.29.21 05:07:47.223 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: CPCLoginResponseMessage@-1745967142[remoteId=136962048763636368, session=1000336245268962532, remoteGuid=42, errors=Login.FAILED] 
[03.29.21 05:07:47.223 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: Error = CPErrors.Login.FAILED : []
[03.29.21 05:07:47.224 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: Send login response to the UI. LoginResponseMessage@650554285[ errors=[CPErrors.Login.FAILED : []]session=1000336240739114212 ]{}
[03.29.21 05:07:47.224 INFO  41696_AUTH-2 backup42.service.ui.UIController] UserActionResponse: LoginResponseMessage@650554285[ errors=[CPErrors.Login.FAILED : []]session=1000336240739114212 ]{}
[03.29.21 05:07:47.224 INFO  41696_AUTH-2 backup42.service.peer.Authorizer] AUTH:: *** END *** Failed after 4sec 
[03.29.21 05:08:12.024 INFO  Thread-33    om.backup42.service.AppLogWriter] WRITE app.log in 74ms
[03.29.21 05:08:14.904 INFO  r3WeDftWkr14 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[03.29.21 05:08:14.904 INFO  r3WeDftWkr14 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
[03.29.21 05:08:59.905 INFO  r3WeDftWkr20 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[03.29.21 05:08:59.906 INFO  r3WeDftWkr20 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
[03.29.21 05:09:44.907 INFO  r3WeDftWkr26 up42.service.peer.PeerController] DENIED! Ignore connect, we are not authorized.
[03.29.21 05:09:44.908 INFO  r3WeDftWkr26 ging.direct.DirectNetworkChannel] Channel became inactive. closedBy=THIS_SIDE, reason='Session close', channel=DIRECT
[03.29.21 05:10:13.587 INFO  ystemWatcher p42.service.peer.CPCConnectCheck] Disconnect from CPC
[03.29.21 05:10:13.588 INFO  ystemWatcher up42.service.peer.PeerController] DISCONNECT and REMOVE CPC

**Comment by spinks88** [comment]
I resolved this issue.

Had crashplan pro installed and not crashplan enterprise.

**Comment by abaum26** [comment]
Could this possibly be related to the forced two-factor authentication?
