### ISSUE TITLE
Version 2.14.0 - constantly waiting for connection

### ISSUE THREAD

**Issue by wdouglascampbell** [jlesage/docker-crashplan-pro#296]
I upgraded two instances of my container to the latest release and now my files are not backing up.  It just constantly indicates that it is waiting for connection.  If I check the destination it says Crashplan Pro Online is disconnected.

Is this an issue with the latest Crashplan release or is it a problem with this release of the Docker container?  Or is it just my bad luck to have this happen on both my containers?

Note that if I revert back to using a previous release everything appears to connect fine again.

Thanks for any guidance.

**Comment by Raainman** [comment]
I have the same issue Crashplan is disconnected.

**Comment by jlesage** [comment]
Can you try to perform the following action:
https://github.com/jlesage/docker-crashplan-pro#device-status-is-waiting-for-connection

**Comment by Raainman** [comment]
Ok I cleared the cache, and now it's now synching ... hopefully this resolves it.

**Comment by wdouglascampbell** [comment]
Nice!  That also worked for me.  Thanks Jocelyn!

**Comment by wdouglascampbell** [comment]
Oops.  I wrote too quickly.  It seems that syncs everything, completes a backup, syncs again and then it loses the connection.  But if I revert to an older version of your container it works fine.

Any other ideas on what I should try?

**Comment by Raainman** [comment]
Same here, lost connection after backup.

**Comment by braderhart** [comment]
I've had this issue twice now with the new version. Initially about a day after upgrading, and recently after running maintenance. Any idea on what is causing it?

**Comment by isustrik** [comment]
Same boat here. Tried clearing the container additionally. Like the others it runs once then waits forever for a connection.

**Comment by vishae** [comment]
I'm also experiencing this issue. I couldn't really figure out where my config folder was to clear it, but I tried reinstalling the latest version of this again, and again it would back up once and then get stuck on "waiting for connection".

Have anyone tried installing an older version?

**Comment by Raainman** [comment]
I went back to 2.13.1 this has no issues. (besides trying to update, but this is normal)

**Comment by jlesage** [comment]
Can you look at `log/service.log.0`, under the folder mapped to `/config`, to see if there is any clue about the issue.

**Comment by met152** [comment]
I can share my log file privately with you. Can you provide an email address?

**Comment by wdouglascampbell** [comment]
I looked in the service.log.0 and I do see the following lines repeated.  I'm wondering if they might led to an explanation.  It looks like it repeats about every minute.

`[03.28.21 01:33:43.486 WARN  318110549>41 com.code42.backup.BackupEntityV1] BC[844110497318110549>41:: TX-CLIENT: Exception performing sync on source side! ...closing, e=java.lang.NullPointerException; BC[844110497318110549>41, sameOwner=f, backupConnected=t, authorized=t, usingForBackup=t, backupNotReadyCode=null, backingUp=f, validating=t, closing=f, keepBlockState=0, con=2021-03-28T01:33:43:301, val=2021-03-28T01:33:43:484, readyCheckTime=2021-03-28T01:33:43:301, MM[BT 844110497318110549>41: openCount=1, initialized = true, dataFiles.open = true, /usr/local/crashplan/cache/41], session=1000169744024271132, hosted=t, hostedCloud=t, replacing=f, selectedForBackup=t, selectedForRestore=f, validationNeeded=f, backupUsageTime=2021-03-28T01:33:43:341, cacheMaintenanceState=null, restoreUtil=BackupClientRestoreDelegate [restoreControl=RestoreReceiveControl@347905317[ , hasRestoreEnv=false, hasRestoreJob=false ], selectedForRestore=false, remoteRestoreStats=RestoreStats[BT sourceId = 844110497318110549, targetId = 41, restoreId = 0, selectedForRestore = false, restoring = false, completed = false, completedTimeInMillis = null, stopwatch = 3day 4hr, numFilesToRestore = 0, numBytesToRestore = 0, numFilesRestored = 0, numBytesRestored = 0, %complete = 100.00%, receiveRateInBytesPerSec(B/s) = 0.000, sendRateInBytesPerSec(B/s) = 0.000, estimatedTimeRemaining = 0.000, fileNumBytesToRestore = 0, fileNumBytesRestored = 0, %completeCurrentFile = 100.00%, numSessionFilesRestored = 0, numSessionBytesRestored = 0, problemCount = 0], pendingRestoresCount=0], BackupQueue[844110497318110549>41, running=f, #tasks=0, sets=[BackupFileTodoSet[backupSetId=1, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1312006665[ path = /usr/local/crashplan/cache/cpft1_41, closed = false, dataSize = 486, headerSize = 0], numTodos = 4, numBytes = 1146]], BackupFileTodoSet[backupSetId=851180787095513583, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1916274478[ path = /usr/local/crashplan/cache/cpft851180787095513583_41, closed = false, dataSize = 10712, headerSize = 0], numTodos = 7, numBytes = 334583]], BackupFileTodoSet[backupSetId=845976214957173417, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1434185968[ path = /usr/local/crashplan/cache/cpft845976214957173417_41, closed = false, dataSize = 12, headerSize = 0], numTodos = 0, numBytes = 0]], BackupFileTodoSet[backupSetId=845976620730919593, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@2019787942[ path = /usr/local/crashplan/cache/cpft845976620730919593_41, closed = false, dataSize = 12, headerSize = 0], numTodos = 0, numBytes = 0]], BackupFileTodoSet[backupSetId=851181372249876295, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1082190345[ path = /usr/local/crashplan/cache/cpft851181372249876295_41, closed = false, dataSize = 189, headerSize = 0], numTodos = 2, numBytes = 29]], BackupFileTodoSet[backupSetId=951839221703004800, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@750633049[ path = /usr/local/crashplan/cache/cpft951839221703004800_41, closed = false, dataSize = 5549, headerSize = 0], numTodos = 49, numBytes = 832106]]], env=null, TodoWorker@369349115[ threadName = BQTodoWkr-41, stopped = true, running = false, thread.isDaemon = false, thread.isAlive = false, thread = Thread[W1431217408_BQTodoWkr-41,5,]], TaskWorker@292911380[ threadName = BQTaskWrk-41, stopped = true, running = false, thread.isDaemon = false, thread.isAlive = false, thread = Thread[W1535721945_BQTaskWrk-41,5,]]] ]; , com.code42.exception.DebugException: BC[844110497318110549>41:: TX-CLIENT: Exception performing sync on source side! ...closing, e=java.lang.NullPointerException; BC[844110497318110549>41, sameOwner=f, backupConnected=t, authorized=t, usingForBackup=t, backupNotReadyCode=null, backingUp=f, validating=t, closing=f, keepBlockState=0, con=2021-03-28T01:33:43:301, val=2021-03-28T01:33:43:484, readyCheckTime=2021-03-28T01:33:43:301, MM[BT 844110497318110549>41: openCount=1, initialized = true, dataFiles.open = true, /usr/local/crashplan/cache/41], session=1000169744024271132, hosted=t, hostedCloud=t, replacing=f, selectedForBackup=t, selectedForRestore=f, validationNeeded=f, backupUsageTime=2021-03-28T01:33:43:341, cacheMaintenanceState=null, restoreUtil=BackupClientRestoreDelegate [restoreControl=RestoreReceiveControl@347905317[ , hasRestoreEnv=false, hasRestoreJob=false ], selectedForRestore=false, remoteRestoreStats=RestoreStats[BT sourceId = 844110497318110549, targetId = 41, restoreId = 0, selectedForRestore = false, restoring = false, completed = false, completedTimeInMillis = null, stopwatch = 3day 4hr, numFilesToRestore = 0, numBytesToRestore = 0, numFilesRestored = 0, numBytesRestored = 0, %complete = 100.00%, receiveRateInBytesPerSec(B/s) = 0.000, sendRateInBytesPerSec(B/s) = 0.000, estimatedTimeRemaining = 0.000, fileNumBytesToRestore = 0, fileNumBytesRestored = 0, %completeCurrentFile = 100.00%, numSessionFilesRestored = 0, numSessionBytesRestored = 0, problemCount = 0], pendingRestoresCount=0], BackupQueue[844110497318110549>41, running=f, #tasks=0, sets=[BackupFileTodoSet[backupSetId=1, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1312006665[ path = /usr/local/crashplan/cache/cpft1_41, closed = false, dataSize = 486, headerSize = 0], numTodos = 4, numBytes = 1146]], BackupFileTodoSet[backupSetId=851180787095513583, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1916274478[ path = /usr/local/crashplan/cache/cpft851180787095513583_41, closed = false, dataSize = 10712, headerSize = 0], numTodos = 7, numBytes = 334583]], BackupFileTodoSet[backupSetId=845976214957173417, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1434185968[ path = /usr/local/crashplan/cache/cpft845976214957173417_41, closed = false, dataSize = 12, headerSize = 0], numTodos = 0, numBytes = 0]], BackupFileTodoSet[backupSetId=845976620730919593, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@2019787942[ path = /usr/local/crashplan/cache/cpft845976620730919593_41, closed = false, dataSize = 12, headerSize = 0], numTodos = 0, numBytes = 0]], BackupFileTodoSet[backupSetId=851181372249876295, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1082190345[ path = /usr/local/crashplan/cache/cpft851181372249876295_41, closed = false, dataSize = 189, headerSize = 0], numTodos = 2, numBytes = 29]], BackupFileTodoSet[backupSetId=951839221703004800, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@750633049[ path = /usr/local/crashplan/cache/cpft951839221703004800_41, closed = false, dataSize = 5549, headerSize = 0], numTodos = 49, numBytes = 832106]]], env=null, TodoWorker@369349115[ threadName = BQTodoWkr-41, stopped = true, running = false, thread.isDaemon = false, thread.isAlive = false, thread = Thread[W1431217408_BQTodoWkr-41,5,]], TaskWorker@292911380[ threadName = BQTaskWrk-41, stopped = true, running = false, thread.isDaemon = false, thread.isAlive = false, thread = Thread[W1535721945_BQTaskWrk-41,5,]]] ];
STACKTRACE:: com.code42.exception.DebugException: BC[844110497318110549>41:: TX-CLIENT: Exception performing sync on source side! ...closing, e=java.lang.NullPointerException; BC[844110497318110549>41, sameOwner=f, backupConnected=t, authorized=t, usingForBackup=t, backupNotReadyCode=null, backingUp=f, validating=t, closing=f, keepBlockState=0, con=2021-03-28T01:33:43:301, val=2021-03-28T01:33:43:484, readyCheckTime=2021-03-28T01:33:43:301, MM[BT 844110497318110549>41: openCount=1, initialized = true, dataFiles.open = true, /usr/local/crashplan/cache/41], session=1000169744024271132, hosted=t, hostedCloud=t, replacing=f, selectedForBackup=t, selectedForRestore=f, validationNeeded=f, backupUsageTime=2021-03-28T01:33:43:341, cacheMaintenanceState=null, restoreUtil=BackupClientRestoreDelegate [restoreControl=RestoreReceiveControl@347905317[ , hasRestoreEnv=false, hasRestoreJob=false ], selectedForRestore=false, remoteRestoreStats=RestoreStats[BT sourceId = 844110497318110549, targetId = 41, restoreId = 0, selectedForRestore = false, restoring = false, completed = false, completedTimeInMillis = null, stopwatch = 3day 4hr, numFilesToRestore = 0, numBytesToRestore = 0, numFilesRestored = 0, numBytesRestored = 0, %complete = 100.00%, receiveRateInBytesPerSec(B/s) = 0.000, sendRateInBytesPerSec(B/s) = 0.000, estimatedTimeRemaining = 0.000, fileNumBytesToRestore = 0, fileNumBytesRestored = 0, %completeCurrentFile = 100.00%, numSessionFilesRestored = 0, numSessionBytesRestored = 0, problemCount = 0], pendingRestoresCount=0], BackupQueue[844110497318110549>41, running=f, #tasks=0, sets=[BackupFileTodoSet[backupSetId=1, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1312006665[ path = /usr/local/crashplan/cache/cpft1_41, closed = false, dataSize = 486, headerSize = 0], numTodos = 4, numBytes = 1146]], BackupFileTodoSet[backupSetId=851180787095513583, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1916274478[ path = /usr/local/crashplan/cache/cpft851180787095513583_41, closed = false, dataSize = 10712, headerSize = 0], numTodos = 7, numBytes = 334583]], BackupFileTodoSet[backupSetId=845976214957173417, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1434185968[ path = /usr/local/crashplan/cache/cpft845976214957173417_41, closed = false, dataSize = 12, headerSize = 0], numTodos = 0, numBytes = 0]], BackupFileTodoSet[backupSetId=845976620730919593, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@2019787942[ path = /usr/local/crashplan/cache/cpft845976620730919593_41, closed = false, dataSize = 12, headerSize = 0], numTodos = 0, numBytes = 0]], BackupFileTodoSet[backupSetId=851181372249876295, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@1082190345[ path = /usr/local/crashplan/cache/cpft851181372249876295_41, closed = false, dataSize = 189, headerSize = 0], numTodos = 2, numBytes = 29]], BackupFileTodoSet[backupSetId=951839221703004800, guid=41, doneLoadingFiles=t, doneLoadingTasks=f, FileTodoSet@750633049[ path = /usr/local/crashplan/cache/cpft951839221703004800_41, closed = false, dataSize = 5549, headerSize = 0], numTodos = 49, numBytes = 832106]]], env=null, TodoWorker@369349115[ threadName = BQTodoWkr-41, stopped = true, running = false, thread.isDaemon = false, thread.isAlive = false, thread = Thread[W1431217408_BQTodoWkr-41,5,]], TaskWorker@292911380[ threadName = BQTaskWrk-41, stopped = true, running = false, thread.isDaemon = false, thread.isAlive = false, thread = Thread[W1535721945_BQTaskWrk-41,5,]]] ];
        at com.code42.backup.BackupEntityV1.logAndClose(BackupEntityV1.java:739)
        at com.code42.backup.BackupEntityV1.logAndClose(BackupEntityV1.java:706)
        at com.code42.backup.manifest.SyncHandler.logAndClose(SyncHandler.java:182)
        at com.code42.backup.manifest.SyncTransactionLogOnSourceWork.performSyncTransactionLogOnSource(SyncTransactionLogOnSourceWork.java:150)
        at com.code42.backup.manifest.SyncTransactionLogOnSourceWork.performWork(SyncTransactionLogOnSourceWork.java:50)
        at com.code42.queue.BackgroundWorkQueue$BackgroundWorker.processWork(BackgroundWorkQueue.java:290)
        at com.code42.queue.BackgroundWorkQueue$BackgroundWorker.run(BackgroundWorkQueue.java:253)
        at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at com.code42.backup.manifest.maintenance.MaintenanceJobState.setKeepBlockStateFromReductionTx(MaintenanceJobState.java:231)
        at com.code42.backup.manifest.maintenance.ClientArchiveV1MaintenanceJob.applyReductionPointTx(ClientArchiveV1MaintenanceJob.java:501)
        at com.code42.backup.manifest.ClientSyncHandler.applyTargetTransactionsAtSource(ClientSyncHandler.java:702)
        at com.code42.backup.manifest.SyncTransactionLogOnSourceWork.performSyncTransactionLogOnSource(SyncTransactionLogOnSourceWork.java:77)
        ... 4 more
`

**Comment by vishae** [comment]
> I went back to 2.13.1 this has no issues. (besides trying to update, but this is normal)

@Raainman how did you revert back to an older version? I can download the older image but don't know how to get the Docker container to load that instead of the latest version.

**Comment by Raainman** [comment]
I'm using portainer, and with that its a matter of using duplicate/edit, and in the 'image' field enter;

jlesage/crashplan-pro:v2.13.1

I gave it a new name too (e.g.' Crashplan_old)  so I can differentiate between the versions.

Using the commandline stop your running container, and create a new container with the line I mentioned above, instead of where you would normaly place "jlesage/crashplan-pro". Also then give it another name.

**Comment by vishae** [comment]
ah, I'm using Synology and I don't know how to do that with synology

**Comment by Raainman** [comment]
I'm a QNAP user myself. On my docker I also run a docker image of portainer, which makes maintaing images a breeze.

**Comment by Raainman** [comment]
In the end this is just a temporary solution, I'm hoping Jocelyn will hopefully resolve the issue.

**Comment by jlesage** [comment]
This issue comes back from time to time.  So far, the solutions that worked for some are:

- Clear the cache.
- Reboot the host.
- Restart from scratch (i.e. clear the appdata folder) and re-adopt the device.

Some users have contacted the CrashPlan support team about the issue, but I never got feedback about the result.

**Comment by jlesage** [comment]
I though about something else that could be tried: rename one of the following directories, one at time:

- `repository`
- `xdg`

These folders are located under the directory that has been mapped to `/config`.  To proceed:

- Stop the container.
- Rename the folder (e.g. `xdg` -> `xdg.old`)
- Start the container.

**Comment by isustrik** [comment]
No immediate luck with renaming the folders, after each rename it was still waiting for connection. I've cleared the cache once again and we'll see if it works now. If not, I'll go through the re-adoption process.

**Comment by jlesage** [comment]
Could you try to have a chat with the CrashPlan support team ?

**Comment by wdouglascampbell** [comment]
Hey Jocelyn,

I started from scratch and so far that appears to be working.  Still monitoring but it really looks like it has worked this time.  I do have a ticket open with Crashplan and since I have another container with the same problem I will likely continue to see if I can work with them to determine if there is a better solution.

Thanks!

**Comment by vishae** [comment]
How would I find out where my config directory is located?
On my Synology there is a docker volume, but there's no app-data folder within it (in fact, the docker volume looks empty).

If I clear/re-install the crashplan docker image, does that clear the cache?

**Comment by isustrik** [comment]
Update, after renaming the folders one at a time as suggested and then clearing the cache folder my instance has started behaving and is now backing up regularly once again.

**Comment by isustrik** [comment]
Unfortunately, I did not clear the cache between renaming the two folders. I only renamed the first folder, started the container, saw it was still failing to connect then renamed the second folder. Only after that failed to connect did I clear the cache. Sorry, I didn't think to clear the cache after each rename. I can happily report that it's backed up successfully over 10 times now so whatever happened it is a permanent fix so far.

**Comment by jlesage** [comment]
Ok, there was no need to clear the cache between renames.  Did you clear the cache before renaming the folders?  Or the clear cache you did after renaming the folder was the first one you attempted?

**Comment by isustrik** [comment]
No, I had cleared the cache a number of times prior to renaming the folders and rebooted the Synology twice before the rename as well. I did not perform any reboots after the rename.

**Comment by Raainman** [comment]
I also had the problem, and I first tried out to clear the cache, which did not help.  Then I created, and ran a container with version 2.13.1 for a couple of days. Yesterday I wanted to get ready to try the rename of the directories with the container that was running 2.14.0, so I shutdown 2.13.1 and started 2.14.0 again, and to my surprise, it synched, and now it is running without further problems! 'Backup completed'.

Very strange, but happy that it is running normal again.

**Comment by wdouglascampbell** [comment]
I retried the renaming of folders that was suggested but initially I did not also clear the cache again.  Yesterday I renamed both folders and cleared the cache and that appears to have done the trick.  I had tried what @Raainman tried multiple times previously and never got things to work that way but both starting from scratch as well as this renaming of folders and clearing the cache seemed to resolve the issue.

I'm going to close this issue since we appear to have two workarounds at the moment.

I had been trying to work with Crashplan support on this but was not making progress with them.  I think they still don't believe there is an issue in the client.

**Comment by jlesage** [comment]
Thanks for the update.

If someone still has the issue, I would like to know if clearing the cache and the `repository` folder is enough.

**Comment by StephanRoemer** [comment]
Hey, 

thanks everyone for their feedback in this thread. Much appreciated. For 5 days I was going crazy and couldn't find the culprit. I also contacted the support, however, I mentioned I am using a Docker. The support still wanted to help me, but his
suggestion was to increase the Java memory, which didn't help. For now, I deleted the cache and the Docker is now resynching the files. Could take some time until this finishes.

**Comment by appdevdoug** [comment]
FYI.  I also was in contact with support and when I updated them on my progress the person finally acknowledge that they are seeing this issue across all of their clients not just Linux.  I happened to have some older logs still so I sent those into them as that is what they were hoping to get to troubleshoot.  If you are still experiencing this I suggest you contact them and ask them what logs you can send their way.

**Comment by Raainman** [comment]
The problem went away for me at first as described above, however it came back. So I tried the rename suggestion. I stopped the docker container, renamed the repository folder, and cleared the cache.

So far it has been running again, I will keep you posted.

**Comment by Raainman** [comment]
It looks like it is running normally now, backups are performed normal, and no more waiting for connection.

**Comment by Raainman** [comment]
Alas, again waiting for connection, I now renamed xdg and cleared the cache. 

Will post results.

**Comment by vishae** [comment]
I cleared cache and it backed up fine, once. Then it went back to waiting for connection.

**Comment by Raainman** [comment]
Mine (after renaming folder xdg, and clearing cache) is still running fine. Something to try @vishae  ?

**Comment by ChuckDavis666** [comment]
As an FYI, I am seeing the similar/same problem on an instance of CrashPlan running on a standalone PC.  Two of the four datasets being backed up are mapped drives on a QNAP NAS.  My wife is running the same version of CrashPlan (8.6.0.1059), backing up just her PC, with no (apparent) problems.

Here is the ticket I opened with Code42.  No response yet.

*************

The app on my PC reports that it has been unable to back up 3 of my 4 datasets for 16.3 days. I can see the app attempting to start a backup and immediately failing with the error message "Unable to connect to destination......" The app reports that my 4th priority dataset, QNAP NAS WHS, was successfully backed up 12 hours ago.

The app is configured to report failed backups after 3 days, but has not reported any problems.

On April 5th I received the weekly e-mail report saying everything is fine and that my system had last been active 20 minutes [prior to the e-mail] and had completed the backup.

The dashboard on my account says that the last activity from my PC was 12 hours ago. This is probably the 4th priority dataset.

Note - Datasets were set up in consultation with Code42. Primary dataset is backed up from 3 AM to 11:59 PM, 7 days a week. 2nd dataset is backed up from midnight to 12:59 AM, 7 days a week. 3rd dataset is backed up from 1 AM to 1:59 AM, 7 days a week. 4th dataset is backed up from 2 AM to 2:59 AM on Sundays.

Here are recent log entries (the last entry is a reboot):

04/07/21 12:00AM [PST & OST Files] Scanning for files to back up
04/07/21 12:00AM [PST & OST Files] Scanning for files completed in < 1 minute: 12 files (6.50GB) found
04/07/21 01:00AM [QNAP NAS LiveData Volume] Scanning for files to back up
04/07/21 01:30AM [QNAP NAS LiveData Volume] Scanning for files completed in 30 minutes: 19,803 files (109.60GB) found
04/07/21 02:00AM [QNAP NAS WHS] Scanning for files to back up
04/07/21 02:57AM [QNAP NAS WHS] Scanning for files completed in 56 minutes: 32,001 files (856.70GB) found
04/07/21 03:00AM [CHUCKS-CARBONX1 Backup Set] Scanning for files to back up
04/07/21 03:36AM [CHUCKS-CARBONX1 Backup Set] Scanning for files completed in 36 minutes: 204,402 files (119.70GB) found
04/08/21 12:00AM [PST & OST Files] Scanning for files to back up
04/08/21 12:00AM [PST & OST Files] Scanning for files completed in < 1 minute: 12 files (6.50GB) found
04/08/21 01:00AM [QNAP NAS LiveData Volume] Scanning for files to back up
04/08/21 01:07AM [QNAP NAS LiveData Volume] Scanning for files completed in 7 minutes: 19,803 files (109.60GB) found
04/08/21 02:00AM [QNAP NAS WHS] Scanning for files to back up
04/08/21 02:12AM [QNAP NAS WHS] Scanning for files completed in 12 minutes: 32,001 files (856.70GB) found
04/08/21 03:00AM [CHUCKS-CARBONX1 Backup Set] Scanning for files to back up
04/08/21 03:11AM [CHUCKS-CARBONX1 Backup Set] Scanning for files completed in 11 minutes: 204,493 files (119.70GB) found
04/08/21 01:48PM Code42 started, version 8.6.0, GUID 617020112849338730

Note - The 4th priority QNAP NAS WHS dataset is only supposed to be backed up on Sundays.

My wife's PC is being backed up successfully, so the problem is unlikely to be a network or firewall issue or a problem with our Norton 360 software.

***********

Unless something about my configuration or environment provides some insight (mapped drives?), it appears likely that this was a buggy CrashPlan release.

**Comment by ChuckDavis666** [comment]
One other point of information.  The QNAP NAS WHS dataset/volume is a static archive of an old Windows Home Server.  There are never any changes to files in the dataset.  The other three datasets have activity.  I wonder if the (apparent, possible) "successful" backup of that dataset is related to its being static.  (It's also possible that "success" means that nothing needed to be backed up.)

**Comment by Raainman** [comment]
Mine is still running fine after rename repository and xdg and clearing cache.

**Comment by ChuckDavis666** [comment]
[Not sure if anybody is seeing this, since issue is closed and I'm a GitHub noob.  Would appreciate a quick ACK.]

A few posts earlier in this thread I reported a similar problem happening with a standalone version of CrashPlan.  Here is the (canned, must be happening a lot) response from Code42.  It does appear that clearing the cache is the key.  Is there a similar "deauthorize" function for CrashPlan running in a container?

To resolve this, we'll want to force a reconnect. Please follow the instructions below:
1.	Open the Code42 CrashPlan app
2.	Use the keyboard shortcut to open the Command Line 
•	Mac: Option+Command+C
•	Windows/Linux: Ctrl+Shift+C
3.	Enter in: deauthorize
4.	This will log you out of the app. 
This will log you out of CrashPlan, so you will need to log back in the application. Afterwards, give CrashPlan some time to rebuild your cache, re-scan your hard drive(s), then see if it is able to connect and resume backing up. It will spend a fair amount of time analyzing block data and resynchronizing with the server, but should resume backing up when it is done.
It will appear your backup is starting over, but as it gets to files already backed up they will be skipped. Since CrashPlan backs up newer and smaller files first, it often takes running for some time until CrashPlan is convincingly doing this, so just keep letting it run.

**Comment by vishae** [comment]
It took me a while to post a follow up on my situation:

- I cleared the cache
- I renamed xdg folder
- crashplan took a while to rescan everything
- it completed one backup
- now everything except for one backup set is "waiting for connection" and has been doing so for two days

I'm afraid this issue is not closed.

**Comment by jlesage** [comment]
@ChuckDavis666, the instructions for Linux should work.

**Comment by vishae** [comment]
Just wondering, would two-factor authentication have anything to do with this?

**Comment by jlesage** [comment]
I'm not sure the problem is directly caused by MFA, since this issue was also seen in other versions of CrashPlan... but I'm not a developer of CrashPlan... so only them really know.

**Comment by ChuckDavis666** [comment]
Has anybody tried Deauthorize, followed by logging back in?  Per postings above, it worked on a standalone PC.

**Comment by wdouglascampbell** [comment]
@ChuckDavis666 I tried the deauthorize option initially but it did not solve the issue for me.

**Comment by ChuckDavis666** [comment]
OK.  Thanks.  Was hoping my similar experience in the Windows rabbit hole might provide some useful information.

**Comment by jwvanderbeck** [comment]
Having this same issue with a new install on Synology.  Waiting for connection but never connects :(
