### ISSUE TITLE
Code43 wasnt able to upgrade but will reattempt in an hour

### ISSUE THREAD

**Issue by vadalus911** [jlesage/docker-crashplan-pro#347]
Using Crashplan for Small Business.

Been getting this for the last couple of weeks. Tried rebooting etc.... Backups looks as though they are still happening although i have been getting email warnings saying they're not.

Anything i can do to force this update? Ideally I dont want to reinstall the docker image again and set up all the shares and go through a full resync again...

Thanks 

[01.04.22 10:31:26.711 INFO  1WeDftWkr575 ervice.peer.PeerVersionValidator] WE have an old version, localVersion=1525200006871, remoteVersion=2000001000000000, remoteGuid=4200
[01.04.22 10:31:26.712 INFO  1WeDftWkr575 42.service.history.HistoryLogger] HISTORY:: Downloading a new version of Code42.
[01.04.22 10:31:26.713 INFO  1WeDftWkr575 .storage.UniversalStorageService] SM:: Saved ServiceModel of 45560 bytes to UDB in 1.182 ms.
[01.04.22 10:31:26.717 INFO  1WeDftWkr575 om.backup42.service.AppLogWriter] WRITE app.log in 4ms
[01.04.22 10:31:26.718 INFO  1WeDftWkr575 .service.upgrade.DownloadManager] UPGRADE:: DownloadManager already running, wakeup...
[01.04.22 10:31:26.718 INFO  2479_DwldMgr .service.upgrade.DownloadManager] UPGRADE:: Downloading patch from https://download.code42.com/installs/agent/cloud/8.8.1/36/upgrade/linux/upgrade5/crashplansmb/1525200006881_36.jar?guid=533318207506219267 to upgrade/upgrade.tmp
[01.04.22 10:31:28.529 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:31:33.529 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:31:38.529 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:31:43.530 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:31:48.530 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:31:53.530 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:31:58.530 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:03.531 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:08.531 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:13.531 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:18.531 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:23.531 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:28.531 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:33.532 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
**[01.04.22 10:32:38.532 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:43.532 INFO  ackupConnWrk rvice.backup.BackupConnectWork**er] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:48.533 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:53.533 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:32:58.533 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:33:03.534 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:33:08.534 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:33:13.534 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:33:18.535 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:33:23.535 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:33:28.535 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
[01.04.22 10:33:33.536 INFO  ackupConnWrk rvice.backup.BackupConnectWorker] BCW:: Connecting 533318207506219267>4200 - peer to backup client.
**[01.04.22 10:33:36.504 WARN  2479_DwldMgr .service.upgrade.DownloadManager] UPGRADE:: Problem generating patch file checksum! - file=upgrade/upgrade.tmp, java.io.FileNotFoundException: upgrade/upgrade.tmp**
STACKTRACE:: java.io.FileNotFoundException: upgrade/upgrade.tmp
        at com.code42.hash.MD5Digest.generateChecksum(MD5Digest.java:262)
        at com.code42.io.FileUtility.generateFileChecksum(FileUtility.java:1008)
        at com.code42.io.FileUtilityService.generateFileChecksum(FileUtilityService.java:537)
        at com.backup42.service.upgrade.DownloadManager.confirmMD5(DownloadManager.java:369)
        at com.backup42.service.upgrade.DownloadManager.downloadPatch(DownloadManager.java:296)
        at com.backup42.service.upgrade.DownloadManager.downloadPatches(DownloadManager.java:231)
        at com.backup42.service.upgrade.DownloadManager.doWork(DownloadManager.java:195)
        at com.code42.utils.AWorker.run(AWorker.java:153)
        at java.base/java.lang.Thread.run(Unknown Source)

[01.04.22 10:33:36.504 WARN  2479_DwldMgr .service.upgrade.DownloadManager] UPGRADE:: Failed to delete upgrade/upgrade.tmp after failed MD5 check following download
[01.04.22 10:33:36.504 WARN  2479_DwldMgr 42.service.history.HistoryLogger] HISTORY:: Download of upgrade failed - version 1525200006881, verification failed.
[01.04.22 10:33:36.505 INFO  2479_DwldMgr .storage.UniversalStorageService] SM:: Saved ServiceModel of 45531 bytes to UDB in 1.106 ms.
[01.04.22 10:33:36.509 INFO  2479_DwldMgr om.backup42.service.AppLogWriter] WRITE app.log in 4ms
[01.04.22 10:33:36.509 WARN  2479_DwldMgr 42.service.history.HistoryLogger] HISTORY:: Unable to apply upgrade(s), retrying in one hour

**Comment by ebdoran** [comment]
Seeing the same behavior on latest.

**Comment by vadalus911** [comment]
In fact I hacked it a bit to get past this step but it won’t upgrade as there’s no bash shell in the container. Is upgrading supposed to work?

**Comment by theRealKLH** [comment]
you have to pull down a new image from docker and rebuild (update) your container.

**Comment by jlesage** [comment]
The version it tries to download indicate that you don't have the latest Docker image.
So as suggested, updating the Docker image will fix the problem.

**Comment by vadalus911** [comment]
Hi,
OK thanks i will do, but does it support updating in general? or do i have to do this everytime a new CrashPlan version comes out? I am using ContinerStation from QNAP which annoyingly does not support updating the image only installing from scratch again.

**Comment by jlesage** [comment]
Yes, CrashPlan self-update is disabled (https://github.com/jlesage/docker-crashplan-pro#why-crashplan-self-update-is-disabled), so you need to update the Docker image to update CrashPlan.

To automatically update containers, you can also install Watchtower (https://github.com/jlesage/docker-crashplan-pro#docker-image-update).

**Comment by vadalus911** [comment]
> Yes, CrashPlan self-update is disabled (https://github.com/jlesage/docker-crashplan-pro#why-crashplan-self-update-is-disabled), so you need to update the Docker image to update CrashPlan.
> 
> To automatically update containers, you can also install Watchtower (https://github.com/jlesage/docker-crashplan-pro#docker-image-update).

many thanks. all understood. thanks for your help

**Comment by jvarrone** [comment]
FWIW ever since I installed Watchtower (at least three years now), I have never experienced any trouble with Crashplan updating itself. Highly recommended…

**Comment by ebdoran** [comment]
I was running this in synology and it didn't seem to refresh the image after looking into this more.  I stopped the container and redeployed my config and it is working fine now.  Thank you.

**Comment by aw-tam** [comment]
> I was running this in synology and it didn't seem to refresh the image after looking into this more. I stopped the container, updated the image, and redeployed my config and it is working fine now. Thank you.

I am also using Synology. How did you "redeploy config"? Is it like export and then import the container settings? Thank you!

**Comment by ebdoran** [comment]
Synology webui --> Docker --> Container --> Settings Import/Export.  
You can also just Registry --> crashplan-pro -->Download Latest.  Then Container --> Action Stop --> Action Reset, then start it again.  You will have to reconnect to crashplan and replace device and skip files and it should keep your old container settings and use the new image.
