### ISSUE TITLE
New Docker instance, [CrashPlanEngine] starting... infinite loop

### ISSUE THREAD

**Issue by jonmatifa** [jlesage/docker-crashplan-pro#363]
I ran into some issues with my crashplan docker instance so I've started completely from scratch and am setting it up like its a brand new install, but crashplan never actually starts. Here's the log output for the docker container,

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 00-app-niceness.sh: executing...
[cont-init.d] 00-app-niceness.sh: exited 0.
[cont-init.d] 00-app-script.sh: executing...
[cont-init.d] 00-app-script.sh: exited 0.
[cont-init.d] 00-app-user-map.sh: executing...
[cont-init.d] 00-app-user-map.sh: exited 0.
[cont-init.d] 00-clean-logmonitor-states.sh: executing...
[cont-init.d] 00-clean-logmonitor-states.sh: exited 0.
[cont-init.d] 00-clean-tmp-dir.sh: executing...
[cont-init.d] 00-clean-tmp-dir.sh: exited 0.
[cont-init.d] 00-set-app-deps.sh: executing...
[cont-init.d] 00-set-app-deps.sh: exited 0.
[cont-init.d] 00-set-home.sh: executing...
[cont-init.d] 00-set-home.sh: exited 0.
[cont-init.d] 00-take-config-ownership.sh: executing...
[cont-init.d] 00-take-config-ownership.sh: exited 0.
[cont-init.d] 00-xdg-runtime-dir.sh: executing...
[cont-init.d] 00-xdg-runtime-dir.sh: exited 0.
[cont-init.d] 10-certs.sh: executing...
[cont-init.d] 10-certs.sh: exited 0.
[cont-init.d] 10-cjk-font.sh: executing...
[cont-init.d] 10-cjk-font.sh: exited 0.
[cont-init.d] 10-nginx.sh: executing...
[cont-init.d] 10-nginx.sh: exited 0.
[cont-init.d] 10-vnc-password.sh: executing...
[cont-init.d] 10-vnc-password.sh: exited 0.
[cont-init.d] 10-web-index.sh: executing...
[cont-init.d] 10-web-index.sh: exited 0.
[cont-init.d] crashplan-pro.sh: executing...
[cont-init.d] crashplan-pro.sh: generating machine-id...
[cont-init.d] crashplan-pro.sh: handling initial run...
[cont-init.d] crashplan-pro.sh: exited 0.
[cont-init.d] validate_max_mem.sh: executing...
[cont-init.d] validate_max_mem.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] starting s6-fdholderd...
[services.d] starting CrashPlanEngine...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
s6-svwait: fatal: timed out
[services.d] starting xvfb...
[xvfb] starting...
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86BrightnessAuto
> Warning:          Could not resolve keysym XF86DisplayOff
> Warning:          Could not resolve keysym XF86Info
> Warning:          Could not resolve keysym XF86AspectRatio
> Warning:          Could not resolve keysym XF86DVD
> Warning:          Could not resolve keysym XF86Audio
> Warning:          Could not resolve keysym XF86ChannelUp
> Warning:          Could not resolve keysym XF86ChannelDown
> Warning:          Could not resolve keysym XF86Break
> Warning:          Could not resolve keysym XF86VideoPhone
> Warning:          Could not resolve keysym XF86ZoomReset
> Warning:          Could not resolve keysym XF86Editor
> Warning:          Could not resolve keysym XF86GraphicsEditor
> Warning:          Could not resolve keysym XF86Presentation
> Warning:          Could not resolve keysym XF86Database
> Warning:          Could not resolve keysym XF86Voicemail
> Warning:          Could not resolve keysym XF86Addressbook
> Warning:          Could not resolve keysym XF86DisplayToggle
> Warning:          Could not resolve keysym XF86SpellCheck
> Warning:          Could not resolve keysym XF86ContextMenu
> Warning:          Could not resolve keysym XF86MediaRepeat
> Warning:          Could not resolve keysym XF8610ChannelsUp
> Warning:          Could not resolve keysym XF8610ChannelsDown
> Warning:          Could not resolve keysym XF86Images
> Warning:          Could not resolve keysym XF86NotificationCenter
> Warning:          Could not resolve keysym XF86PickupPhone
> Warning:          Could not resolve keysym XF86HangupPhone
> Warning:          Could not resolve keysym XF86Fn
> Warning:          Could not resolve keysym XF86Fn_Esc
> Warning:          Could not resolve keysym XF86FnRightShift
> Warning:          Could not resolve keysym XF86Numeric0
> Warning:          Could not resolve keysym XF86Numeric1
> Warning:          Could not resolve keysym XF86Numeric2
> Warning:          Could not resolve keysym XF86Numeric3
> Warning:          Could not resolve keysym XF86Numeric4
> Warning:          Could not resolve keysym XF86Numeric5
> Warning:          Could not resolve keysym XF86Numeric6
> Warning:          Could not resolve keysym XF86Numeric7
> Warning:          Could not resolve keysym XF86Numeric8
> Warning:          Could not resolve keysym XF86Numeric9
> Warning:          Could not resolve keysym XF86NumericStar
> Warning:          Could not resolve keysym XF86NumericPound
> Warning:          Could not resolve keysym XF86NumericA
> Warning:          Could not resolve keysym XF86NumericB
> Warning:          Could not resolve keysym XF86NumericC
> Warning:          Could not resolve keysym XF86NumericD
> Warning:          Could not resolve keysym XF86CameraFocus
> Warning:          Could not resolve keysym XF86WPSButton
> Warning:          Could not resolve keysym XF86CameraZoomIn
> Warning:          Could not resolve keysym XF86CameraZoomOut
> Warning:          Could not resolve keysym XF86CameraUp
> Warning:          Could not resolve keysym XF86CameraDown
> Warning:          Could not resolve keysym XF86CameraLeft
> Warning:          Could not resolve keysym XF86CameraRight
> Warning:          Could not resolve keysym XF86AttendantOn
> Warning:          Could not resolve keysym XF86AttendantOff
> Warning:          Could not resolve keysym XF86AttendantToggle
> Warning:          Could not resolve keysym XF86LightsToggle
> Warning:          Could not resolve keysym XF86ALSToggle
> Warning:          Could not resolve keysym XF86Buttonconfig
> Warning:          Could not resolve keysym XF86Taskmanager
> Warning:          Could not resolve keysym XF86Journal
> Warning:          Could not resolve keysym XF86ControlPanel
> Warning:          Could not resolve keysym XF86AppSelect
> Warning:          Could not resolve keysym XF86Screensaver
> Warning:          Could not resolve keysym XF86VoiceCommand
> Warning:          Could not resolve keysym XF86Assistant
> Warning:          Could not resolve keysym XF86BrightnessMin
> Warning:          Could not resolve keysym XF86BrightnessMax
> Warning:          Could not resolve keysym XF86KbdInputAssistPrev
> Warning:          Could not resolve keysym XF86KbdInputAssistNext
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistAccept
> Warning:          Could not resolve keysym XF86KbdInputAssistCancel
> Warning:          Could not resolve keysym XF86RightUp
> Warning:          Could not resolve keysym XF86RightDown
> Warning:          Could not resolve keysym XF86LeftUp
> Warning:          Could not resolve keysym XF86LeftDown
> Warning:          Could not resolve keysym XF86RootMenu
> Warning:          Could not resolve keysym XF86MediaTopMenu
> Warning:          Could not resolve keysym XF86Numeric11
> Warning:          Could not resolve keysym XF86Numeric12
> Warning:          Could not resolve keysym XF86AudioDesc
> Warning:          Could not resolve keysym XF863DMode
> Warning:          Could not resolve keysym XF86NextFavorite
> Warning:          Could not resolve keysym XF86StopRecord
> Warning:          Could not resolve keysym XF86PauseRecord
> Warning:          Could not resolve keysym XF86VOD
> Warning:          Could not resolve keysym XF86Unmute
> Warning:          Could not resolve keysym XF86FastReverse
> Warning:          Could not resolve keysym XF86SlowReverse
> Warning:          Could not resolve keysym XF86Data
> Warning:          Could not resolve keysym XF86OnScreenKeyboard
> Warning:          Could not resolve keysym XF86PrivacyScreenToggle
> Warning:          Could not resolve keysym XF86SelectiveScreenshot
> Warning:          Could not resolve keysym XF86Macro1
> Warning:          Could not resolve keysym XF86Macro2
> Warning:          Could not resolve keysym XF86Macro3
> Warning:          Could not resolve keysym XF86Macro4
> Warning:          Could not resolve keysym XF86Macro5
> Warning:          Could not resolve keysym XF86Macro6
> Warning:          Could not resolve keysym XF86Macro7
> Warning:          Could not resolve keysym XF86Macro8
> Warning:          Could not resolve keysym XF86Macro9
> Warning:          Could not resolve keysym XF86Macro10
> Warning:          Could not resolve keysym XF86Macro11
> Warning:          Could not resolve keysym XF86Macro12
> Warning:          Could not resolve keysym XF86Macro13
> Warning:          Could not resolve keysym XF86Macro14
> Warning:          Could not resolve keysym XF86Macro15
> Warning:          Could not resolve keysym XF86Macro16
> Warning:          Could not resolve keysym XF86Macro17
> Warning:          Could not resolve keysym XF86Macro18
> Warning:          Could not resolve keysym XF86Macro19
> Warning:          Could not resolve keysym XF86Macro20
> Warning:          Could not resolve keysym XF86Macro21
> Warning:          Could not resolve keysym XF86Macro22
> Warning:          Could not resolve keysym XF86Macro23
> Warning:          Could not resolve keysym XF86Macro24
> Warning:          Could not resolve keysym XF86Macro25
> Warning:          Could not resolve keysym XF86Macro26
> Warning:          Could not resolve keysym XF86Macro27
> Warning:          Could not resolve keysym XF86Macro28
> Warning:          Could not resolve keysym XF86Macro29
> Warning:          Could not resolve keysym XF86Macro30
> Warning:          Could not resolve keysym XF86MacroRecordStart
> Warning:          Could not resolve keysym XF86MacroRecordStop
> Warning:          Could not resolve keysym XF86MacroPresetCycle
> Warning:          Could not resolve keysym XF86MacroPreset1
> Warning:          Could not resolve keysym XF86MacroPreset2
> Warning:          Could not resolve keysym XF86MacroPreset3
> Warning:          Could not resolve keysym XF86KbdLcdMenu1
> Warning:          Could not resolve keysym XF86KbdLcdMenu2
> Warning:          Could not resolve keysym XF86KbdLcdMenu3
> Warning:          Could not resolve keysym XF86KbdLcdMenu4
> Warning:          Could not resolve keysym XF86KbdLcdMenu5
Errors from xkbcomp are not fatal to the X server
[services.d] starting nginx...
The XKEYBOARD keymap compiler (xkbcomp) reports:
> Warning:          Could not resolve keysym XF86BrightnessAuto
> Warning:          Could not resolve keysym XF86DisplayOff
> Warning:          Could not resolve keysym XF86Info
> Warning:          Could not resolve keysym XF86AspectRatio
> Warning:          Could not resolve keysym XF86DVD
> Warning:          Could not resolve keysym XF86Audio
> Warning:          Could not resolve keysym XF86ChannelUp
> Warning:          Could not resolve keysym XF86ChannelDown
> Warning:          Could not resolve keysym XF86Break
> Warning:          Could not resolve keysym XF86VideoPhone
> Warning:          Could not resolve keysym XF86ZoomReset
> Warning:          Could not resolve keysym XF86Editor
> Warning:          Could not resolve keysym XF86GraphicsEditor
> Warning:          Could not resolve keysym XF86Presentation
> Warning:          Could not resolve keysym XF86Database
> Warning:          Could not resolve keysym XF86Voicemail
> Warning:          Could not resolve keysym XF86Addressbook
> Warning:          Could not resolve keysym XF86DisplayToggle
> Warning:          Could not resolve keysym XF86SpellCheck
> Warning:          Could not resolve keysym XF86ContextMenu
> Warning:          Could not resolve keysym XF86MediaRepeat
> Warning:          Could not resolve keysym XF8610ChannelsUp
> Warning:          Could not resolve keysym XF8610ChannelsDown
> Warning:          Could not resolve keysym XF86Images
> Warning:          Could not resolve keysym XF86NotificationCenter
> Warning:          Could not resolve keysym XF86PickupPhone
> Warning:          Could not resolve keysym XF86HangupPhone
> Warning:          Could not resolve keysym XF86Fn
> Warning:          Could not resolve keysym XF86Fn_Esc
> Warning:          Could not resolve keysym XF86FnRightShift
> Warning:          Could not resolve keysym XF86Numeric0
> Warning:          Could not resolve keysym XF86Numeric1
> Warning:          Could not resolve keysym XF86Numeric2
> Warning:          Could not resolve keysym XF86Numeric3
> Warning:          Could not resolve keysym XF86Numeric4
> Warning:          Could not resolve keysym XF86Numeric5
> Warning:          Could not resolve keysym XF86Numeric6
> Warning:          Could not resolve keysym XF86Numeric7
> Warning:          Could not resolve keysym XF86Numeric8
> Warning:          Could not resolve keysym XF86Numeric9
> Warning:          Could not resolve keysym XF86NumericStar
> Warning:          Could not resolve keysym XF86NumericPound
> Warning:          Could not resolve keysym XF86NumericA
> Warning:          Could not resolve keysym XF86NumericB
> Warning:          Could not resolve keysym XF86NumericC
> Warning:          Could not resolve keysym XF86NumericD
> Warning:          Could not resolve keysym XF86CameraFocus
> Warning:          Could not resolve keysym XF86WPSButton
> Warning:          Could not resolve keysym XF86CameraZoomIn
> Warning:          Could not resolve keysym XF86CameraZoomOut
> Warning:          Could not resolve keysym XF86CameraUp
> Warning:          Could not resolve keysym XF86CameraDown
> Warning:          Could not resolve keysym XF86CameraLeft
> Warning:          Could not resolve keysym XF86CameraRight
> Warning:          Could not resolve keysym XF86AttendantOn
> Warning:          Could not resolve keysym XF86AttendantOff
> Warning:          Could not resolve keysym XF86AttendantToggle
> Warning:          Could not resolve keysym XF86LightsToggle
> Warning:          Could not resolve keysym XF86ALSToggle
> Warning:          Could not resolve keysym XF86Buttonconfig
> Warning:          Could not resolve keysym XF86Taskmanager
> Warning:          Could not resolve keysym XF86Journal
> Warning:          Could not resolve keysym XF86ControlPanel
> Warning:          Could not resolve keysym XF86AppSelect
> Warning:          Could not resolve keysym XF86Screensaver
> Warning:          Could not resolve keysym XF86VoiceCommand
> Warning:          Could not resolve keysym XF86Assistant
> Warning:          Could not resolve keysym XF86BrightnessMin
> Warning:          Could not resolve keysym XF86BrightnessMax
> Warning:          Could not resolve keysym XF86KbdInputAssistPrev
> Warning:          Could not resolve keysym XF86KbdInputAssistNext
> Warning:          Could not resolve keysym XF86KbdInputAssistPrevgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistNextgroup
> Warning:          Could not resolve keysym XF86KbdInputAssistAccept
> Warning:          Could not resolve keysym XF86KbdInputAssistCancel
> Warning:          Could not resolve keysym XF86RightUp
> Warning:          Could not resolve keysym XF86RightDown
> Warning:          Could not resolve keysym XF86LeftUp
> Warning:          Could not resolve keysym XF86LeftDown
> Warning:          Could not resolve keysym XF86RootMenu
> Warning:          Could not resolve keysym XF86MediaTopMenu
> Warning:          Could not resolve keysym XF86Numeric11
> Warning:          Could not resolve keysym XF86Numeric12
> Warning:          Could not resolve keysym XF86AudioDesc
> Warning:          Could not resolve keysym XF863DMode
> Warning:          Could not resolve keysym XF86NextFavorite
> Warning:          Could not resolve keysym XF86StopRecord
> Warning:          Could not resolve keysym XF86PauseRecord
> Warning:          Could not resolve keysym XF86VOD
> Warning:          Could not resolve keysym XF86Unmute
> Warning:          Could not resolve keysym XF86FastReverse
> Warning:          Could not resolve keysym XF86SlowReverse
> Warning:          Could not resolve keysym XF86Data
> Warning:          Could not resolve keysym XF86OnScreenKeyboard
> Warning:          Could not resolve keysym XF86PrivacyScreenToggle
> Warning:          Could not resolve keysym XF86SelectiveScreenshot
> Warning:          Could not resolve keysym XF86Macro1
> Warning:          Could not resolve keysym XF86Macro2
> Warning:          Could not resolve keysym XF86Macro3
> Warning:          Could not resolve keysym XF86Macro4
> Warning:          Could not resolve keysym XF86Macro5
> Warning:          Could not resolve keysym XF86Macro6
> Warning:          Could not resolve keysym XF86Macro7
> Warning:          Could not resolve keysym XF86Macro8
> Warning:          Could not resolve keysym XF86Macro9
> Warning:          Could not resolve keysym XF86Macro10
> Warning:          Could not resolve keysym XF86Macro11
> Warning:          Could not resolve keysym XF86Macro12
> Warning:          Could not resolve keysym XF86Macro13
> Warning:          Could not resolve keysym XF86Macro14
> Warning:          Could not resolve keysym XF86Macro15
> Warning:          Could not resolve keysym XF86Macro16
> Warning:          Could not resolve keysym XF86Macro17
> Warning:          Could not resolve keysym XF86Macro18
> Warning:          Could not resolve keysym XF86Macro19
> Warning:          Could not resolve keysym XF86Macro20
> Warning:          Could not resolve keysym XF86Macro21
> Warning:          Could not resolve keysym XF86Macro22
> Warning:          Could not resolve keysym XF86Macro23
> Warning:          Could not resolve keysym XF86Macro24
> Warning:          Could not resolve keysym XF86Macro25
> Warning:          Could not resolve keysym XF86Macro26
> Warning:          Could not resolve keysym XF86Macro27
> Warning:          Could not resolve keysym XF86Macro28
> Warning:          Could not resolve keysym XF86Macro29
> Warning:          Could not resolve keysym XF86Macro30
> Warning:          Could not resolve keysym XF86MacroRecordStart
> Warning:          Could not resolve keysym XF86MacroRecordStop
> Warning:          Could not resolve keysym XF86MacroPresetCycle
> Warning:          Could not resolve keysym XF86MacroPreset1
> Warning:          Could not resolve keysym XF86MacroPreset2
> Warning:          Could not resolve keysym XF86MacroPreset3
> Warning:          Could not resolve keysym XF86KbdLcdMenu1
> Warning:          Could not resolve keysym XF86KbdLcdMenu2
> Warning:          Could not resolve keysym XF86KbdLcdMenu3
> Warning:          Could not resolve keysym XF86KbdLcdMenu4
> Warning:          Could not resolve keysym XF86KbdLcdMenu5
Errors from xkbcomp are not fatal to the X server
[services.d] starting certsmonitor...
[nginx] starting...
[services.d] starting x11vnc...
[services.d] starting statusmonitor...
[certsmonitor] disabling service: secure connection not enabled.
[services.d] starting openbox...
[x11vnc] starting...
[openbox] starting...
[statusmonitor] starting...
24/02/2022 21:07:48 passing arg to libvncserver: -rfbport
24/02/2022 21:07:48 passing arg to libvncserver: 5900
24/02/2022 21:07:48 passing arg to libvncserver: -rfbportv6
24/02/2022 21:07:48 passing arg to libvncserver: -1
24/02/2022 21:07:48 passing arg to libvncserver: -httpportv6
24/02/2022 21:07:48 passing arg to libvncserver: -1
24/02/2022 21:07:48 passing arg to libvncserver: -desktop
24/02/2022 21:07:48 passing arg to libvncserver: CrashPlan for Small Business
24/02/2022 21:07:48 x11vnc version: 0.9.14 lastmod: 2015-11-14  pid: 953
24/02/2022 21:07:48 Using X display :0
24/02/2022 21:07:48 rootwin: 0x43 reswin: 0x200001 dpy: 0x72ee040
24/02/2022 21:07:48
24/02/2022 21:07:48 ------------------ USEFUL INFORMATION ------------------
24/02/2022 21:07:48 X DAMAGE available on display, using it for polling hints.
24/02/2022 21:07:48   To disable this behavior use: '-noxdamage'
24/02/2022 21:07:48
24/02/2022 21:07:48   Most compositing window managers like 'compiz' or 'beryl'
24/02/2022 21:07:48   cause X DAMAGE to fail, and so you may not see any screen
24/02/2022 21:07:48   updates via VNC.  Either disable 'compiz' (recommended) or
24/02/2022 21:07:48   supply the x11vnc '-noxdamage' command line option.
24/02/2022 21:07:48 X COMPOSITE available on display, using it for window polling.
24/02/2022 21:07:48   To disable this behavior use: '-noxcomposite'
24/02/2022 21:07:48
24/02/2022 21:07:48 Wireframing: -wireframe mode is in effect for window moves.
24/02/2022 21:07:48   If this yields undesired behavior (poor response, painting
24/02/2022 21:07:48   errors, etc) it may be disabled:
24/02/2022 21:07:48    - use '-nowf' to disable wireframing completely.
24/02/2022 21:07:48    - use '-nowcr' to disable the Copy Rectangle after the
24/02/2022 21:07:48      moved window is released in the new position.
24/02/2022 21:07:48   Also see the -help entry for tuning parameters.
24/02/2022 21:07:48   You can press 3 Alt_L's (Left "Alt" key) in a row to
24/02/2022 21:07:48   repaint the screen, also see the -fixscreen option for
24/02/2022 21:07:48   periodic repaints.
24/02/2022 21:07:48 GrabServer control via XTEST.
24/02/2022 21:07:48
24/02/2022 21:07:48 Scroll Detection: -scrollcopyrect mode is in effect to
24/02/2022 21:07:48   use RECORD extension to try to detect scrolling windows
24/02/2022 21:07:48   (induced by either user keystroke or mouse input).
24/02/2022 21:07:48   If this yields undesired behavior (poor response, painting
24/02/2022 21:07:48   errors, etc) it may be disabled via: '-noscr'
24/02/2022 21:07:48   Also see the -help entry for tuning parameters.
24/02/2022 21:07:48   You can press 3 Alt_L's (Left "Alt" key) in a row to
24/02/2022 21:07:48   repaint the screen, also see the -fixscreen option for
24/02/2022 21:07:48   periodic repaints.
24/02/2022 21:07:48
24/02/2022 21:07:48 XKEYBOARD: number of keysyms per keycode 7 is greater
24/02/2022 21:07:48   than 4 and 51 keysyms are mapped above 4.
24/02/2022 21:07:48   Automatically switching to -xkb mode.
24/02/2022 21:07:48   If this makes the key mapping worse you can
24/02/2022 21:07:48   disable it with the "-noxkb" option.
24/02/2022 21:07:48   Also, remember "-remap DEAD" for accenting characters.
24/02/2022 21:07:48
24/02/2022 21:07:48 X FBPM extension not supported.
Xlib:  extension "DPMS" missing on display ":0".
24/02/2022 21:07:48 X display is not capable of DPMS.
24/02/2022 21:07:48 --------------------------------------------------------
24/02/2022 21:07:48
24/02/2022 21:07:48 Default visual ID: 0x21
24/02/2022 21:07:48 Read initial data from X display into framebuffer.
24/02/2022 21:07:48 initialize_screen: fb_depth/fb_bpp/fb_Bpl 24/32/5120
24/02/2022 21:07:48
24/02/2022 21:07:48 X display :0 is 32bpp depth=24 true color
24/02/2022 21:07:48
24/02/2022 21:07:48 Listening for VNC connections on TCP port 5900
24/02/2022 21:07:48
24/02/2022 21:07:48 Xinerama is present and active (e.g. multi-head).
24/02/2022 21:07:48 Xinerama: number of sub-screens: 1
24/02/2022 21:07:48 Xinerama: no blackouts needed (only one sub-screen)
24/02/2022 21:07:48
24/02/2022 21:07:48 fb read rate: 1494 MB/sec
24/02/2022 21:07:48 fast read: reset -wait  ms to: 10
24/02/2022 21:07:48 fast read: reset -defer ms to: 10
24/02/2022 21:07:48 The X server says there are 10 mouse buttons.
24/02/2022 21:07:48 screen setup finished.
24/02/2022 21:07:48

The VNC desktop is:      b806a8fc61e0:0
PORT=5900

******************************************************************************
Have you tried the x11vnc '-ncache' VNC client-side pixel caching feature yet?

The scheme stores pixel data offscreen on the VNC viewer side for faster
retrieval.  It should work with any VNC viewer.  Try it by running:

    x11vnc -ncache 10 ...

One can also add -ncache_cr for smooth 'copyrect' window motion.
More info: http://www.karlrunge.com/x11vnc/faq.html#faq-client-caching

[services.d] starting logmonitor...
[services.d] starting app...
[logmonitor] starting...
[app] starting CrashPlan for Small Business...
[services.d] done.
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...
[CrashPlanEngine] starting...`

**Comment by jlesage** [comment]
How did you create the container (what is your `docker run` command) ?

**Comment by jonmatifa** [comment]
docker run -d \
    --name=crashplan-pro \
    -p 5800:5800 \
    -v /saltlake/var/crashplan-data:/config:rw \
    -v /saltlake:/storage:ro \
    -v /media/encrypted:/media/encrypted:ro \
    jlesage/crashplan-pro

/saltlake is a zfs pool, are there file system limitations for the /config folder?

**Comment by srudin** [comment]
Your log is saying
"Listening for VNC connections on TCP port 5900"
but your command shows you specify port 5800? Maybe unrelated, just had me wondering.

**Comment by jlesage** [comment]
To check why the engine is not starting, you can try to look at the following log files, located under `/saltlake/var/crashplan-data/log`:
- engine_error.log
- engine_output.log
- service.log.0

**Comment by jonmatifa** [comment]
I made an ext4 volume on my ZFS array and made that the /config volume, now the docker instance starts right up. So it seems theres a file system incompatibility perhaps. 

Here are the log files form the previous attempt (ZFS file system)

**engine_error.log**
`WARNING: Illegal reflective access by com.code42.crypto.jce.ec.EcCurveLookup (file:/usr/local/crashplan/lib/c42-crypto-impl-15.2.3.jar) to method sun.security                                                                                               .util.CurveDB.lookup(java.security.spec.ECParameterSpec)
WARNING: Please consider reporting this to the maintainers of com.code42.crypto.jce.ec.EcCurveLookup
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`

**engine_output.log**
`Initializing the JVM arguments.
Creating the Java virtual machine.
Number of arguments: 20
Java virtual machine created.
Starting service.
[02.24.22 21:12:19.314 INFO  main             com.code42.utils.ClassFinder] Loaded classpaths in 1261 ms
Service is complete.
Launching as root
Paths:
  cwd:      /usr/local/crashplan
  appData:  /usr/local/crashplan
  jvm_args: /usr/local/crashplan/conf/jvm_args
JVM arguments in use:
-Dsun.jnu.encoding=UTF-8
-Dfile.encoding=UTF-8
-Dsun.net.inetaddr.ttl=300
-Dnetworkaddress.cache.ttl=300
-Dsun.net.inetaddr.negative.ttl=0
-Dnetworkaddress.cache.negative.ttl=0
-Dapp=Code42Service
-DappBaseName=Code42
-Djna.nosys=true
-Djava.awt.headless=true
-DCode42=Code42
-Dnashorn.args=--no-deprecation-warning
-Dc42.installation.enforcement.enabled=true
-XX:-ShrinkHeapInSteps
-XX:MaxHeapFreeRatio=30
-XX:MinHeapFreeRatio=15
-Djava.library.path=/usr/local/crashplan/nlib
-Djna.library.path=/usr/local/crashplan/nlib
-Dc42.log.config=/usr/local/crashplan/conf/service.log.xml
Arguments in use:`

**service.log.0**
`"Reference Handler" #6 daemon prio=10 tid=0x0000000000000002 nid=0x6 runnable [0x0000000065c3d39f]
         java.lang.Thread.State: RUNNABLE
        at java.base@11.0.12/java.lang.ref.Reference.waitForReferencePendingList(Native Method)
        at java.base@11.0.12/java.lang.ref.Reference.processPendingReferences(Unknown Source)
        at java.base@11.0.12/java.lang.ref.Reference$ReferenceHandler.run(Unknown Source)

"Finalizer" #5 daemon prio=8 tid=0x0000000000000003 nid=0x5 in Object.wait() [0x000000000e83e8fb]
         java.lang.Thread.State: WAITING (on object monitor)
        at java.base@11.0.12/java.lang.Object.wait(Native Method)
        at java.base@11.0.12/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.base@11.0.12/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.base@11.0.12/java.lang.ref.Finalizer$FinalizerThread.run(Unknown Source)

"Signal Dispatcher" #4 daemon prio=9 tid=0x0000000000000004 nid=0x4 runnable [0x000000001ec37dc1]
         java.lang.Thread.State: RUNNABLE

"Common-Cleaner" #3 daemon prio=8 tid=0x000000000000000a nid=0x3 in Object.wait() [0x000000003494183d]
         java.lang.Thread.State: TIMED_WAITING (on object monitor)
        at java.base@11.0.12/java.lang.Object.wait(Native Method)
        at java.base@11.0.12/java.lang.ref.ReferenceQueue.remove(Unknown Source)
        at java.base@11.0.12/jdk.internal.ref.CleanerImpl.run(Unknown Source)
        at java.base@11.0.12/java.lang.Thread.run(Unknown Source)
        at java.base@11.0.12/jdk.internal.misc.InnocuousThread.run(Unknown Source)

"Thread-0" #2 prio=5 tid=0x000000000000000d nid=0x2 runnable [0x000000003bb04b53]
         java.lang.Thread.State: RUNNABLE
        at java.base@11.0.12/java.lang.Thread.dumpThreads(Native Method)
        at java.base@11.0.12/java.lang.Thread.getAllStackTraces(Unknown Source)
        at app//com.code42.logging.ThreadDumpLogger.threadDump(ThreadDumpLogger.java:99)
        at app//com.code42.logging.ThreadDumpLogger.dumpThreads(ThreadDumpLogger.java:57)
        at app//com.code42.logging.ThreadDumpLogger.dumpThreadsToComAndThreadLogs(ThreadDumpLogger.java:91)
        at app//com.backup42.service.CPService.dumpThreads(CPService.java:1419)
        at app//com.backup42.service.CPService.cleanup(CPService.java:1291)
        at app//com.backup42.service.CPService.lambda$start$0(CPService.java:423)
        at app//com.backup42.service.CPService$$Lambda$206/0x000000080043c840.run(Unknown Source)
        at java.base@11.0.12/java.lang.Thread.run(Unknown Source)

"process reaper" #1 daemon prio=10 tid=0x000000000000000e nid=0x1 waiting on condition [0x000000004fb06a1b]
         java.lang.Thread.State: TIMED_WAITING (parking)
        at java.base@11.0.12/jdk.internal.misc.Unsafe.park(Native Method)
        at java.base@11.0.12/java.util.concurrent.locks.LockSupport.parkNanos(Unknown Source)
        at java.base@11.0.12/java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(Unknown Source)
        at java.base@11.0.12/java.util.concurrent.SynchronousQueue$TransferStack.transfer(Unknown Source)
        at java.base@11.0.12/java.util.concurrent.SynchronousQueue.poll(Unknown Source)
        at java.base@11.0.12/java.util.concurrent.ThreadPoolExecutor.getTask(Unknown Source)
        at java.base@11.0.12/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.base@11.0.12/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.base@11.0.12/java.lang.Thread.run(Unknown Source)`

**Comment by jlesage** [comment]
Unfortunately I don't see anything obvious from what you provided.

But you are right, CrashPlan is probably using an operation not supported by the ZFS filesystem...
