### ISSUE TITLE
Unable to start - no such file libgcc_s.so.1

### ISSUE THREAD

**Issue by hooper303** [jlesage/docker-crashplan-pro#39]
Setup a new docker today, and it won't startup. The error is as follows:
01.11.18 19:56:57.367 ERROR main           com.backup42.service.CPService] Error starting up, java.lang.UnsatisfiedLinkError: libgcc_s.so.1: cannot open shared object file: No such file or directory
STACKTRACE:: java.lang.UnsatisfiedLinkError: libgcc_s.so.1: cannot open shared object file: No such file or directory
	at com.sun.jna.Native.open(Native Method)
	at com.sun.jna.NativeLibrary.loadLibrary(NativeLibrary.java:288)
	at com.sun.jna.NativeLibrary.getInstance(NativeLibrary.java:427)
	at com.sun.jna.Native.register(Native.java:1647)
	at com.sun.jna.Native.register(Native.java:1360)
	at com.code42.jna.leveldb.LevelDBJNA.<clinit>(LevelDBJNA.java:30)
	at com.code42.jna.leveldb.api.DBFactory.toNativeComparator(DBFactory.java:104)
	at com.code42.jna.leveldb.api.DBFactory.destroyDB(DBFactory.java:153)
	at com.code42.archive.leveldb.LevelDBFactory.destroyDB(LevelDBFactory.java:23)
	at com.code42.archive.AbstractLevelDBFile.delete(AbstractLevelDBFile.java:117)
	at com.code42.service.storage.AuthorizedStorageService.delete(AuthorizedStorageService.java:161)
	at com.code42.service.storage.AuthorizedStorageValidator.deleteStorage(AuthorizedStorageValidator.java:59)
	at com.backup42.service.CPService.startCheckAuthorizedStorage(CPService.java:795)
	at com.backup42.service.CPService.start(CPService.java:613)
	at com.backup42.service.CPService.main(CPService.java:2062)

Any ideas on troubleshooting?

**Comment by jlesage** [comment]
Yes a new image with a fix for this is in the build queue.  Should be available very soon.

While waiting, you can run `docker exec <container name> /usr/glibc-compat/sbin/ldconfig` to fix the problem.

**Comment by jlesage** [comment]
New image available with fix for this issue.
